(function(g){var window=this;var d1=function(a){var b={languageCode:a.i,languageName:a.l,displayName:g.tz(a),kind:a.o,name:a.u,id:a.Ca,is_servable:a.B,is_default:a.isDefault,is_translateable:a.D,vss_id:a.A};a.g&&(b.translationLanguage=a.g);return b},e1=function(a){return a.g?a.g.languageCode:a.i},goa=function(a,b){var c=new g.sz;
c.i=a.i;c.l=a.l;c.u=a.u;c.o=a.o;c.isDefault=!1;c.B=a.B;c.D=a.D;c.A=a.A;c.F=a.F;c.g=b;return c},f1=function(a){if(!hoa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(ioa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},joa=function(){this.i=[];
this.g=[]},g1=function(a,b){return b?a.g.concat(a.i):a.g},h1=function(a,b){switch(b.o){case "asr":var c=a.i;
g.eb(c,(0,g.y)(b.Nq,b))||c.push(b);break;default:c=a.g,g.eb(c,(0,g.y)(b.Nq,b))||c.push(b)}},i1=function(){g.E.call(this);
this.i=new joa;this.u=[]},j1=function(a,b,c){i1.call(this,a);
this.g=null;this.u=b.mu;this.l=c},k1=function(){this.Ta=[]},l1=function(a,b,c,d,e,f){g.E.call(this);
this.I=a;this.o=b;this.A=new k1;this.g=null;this.F=d;this.P=f;this.i=this.l=null;this.D=c;this.B=e||!1;this.H=new g.L(this.Bw,1E3,this);g.G(this,this.H);this.u=new g.es(this);g.G(this,this.u);g.P(g.V(b).experiments,"html5_disable_captions_seek_complete")?this.u.K(b,"seekto",this.kx):this.u.K(b,"seekcomplete",this.fF);this.kx(b.getCurrentTime());this.Bw()},m1=function(a,b){b-=a.o.hc();
var c=a.g;a.g=g.ab(a.D.nf(b).g);c!=a.g&&a.P&&a.P()},n1=function(a,b){var c=g.Kv(b,a.I,{}).Eb(),d={format:"RAW",
withCredentials:!0};a.B&&(d.responseType="arraybuffer");a.i=g.tr(c,d,3,100).then((0,g.y)(a.LJ,a));a.l=b;c=a.A;d=a.l.g[0].i;var e=g.zb(c.Ta,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Ta[e-1]&&e<c.Ta.length&&1==c.Ta[e]-d?(g.lb(c.Ta,e),g.lb(c.Ta,e-1)):0<e&&1==d-c.Ta[e-1]?c.Ta[e-1]=d:e<c.Ta.length&&1==c.Ta[e]-d?c.Ta[e]=d:(g.ub(c.Ta,e,0,d),g.ub(c.Ta,e+1,0,d)))},o1=function(a,b){i1.call(this,g.V(b));
this.g=a;this.B=b;this.l=null;this.o=!1;this.A=g.dz(g.V(this.B))&&!this.g.i},p1=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.lU(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.sz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},koa=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},q1=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.lU(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},r1=function(a,b,c,d,e){i1.call(this,e||null);
c=c||g.Cq(a).hl||"";c=c.split("_").join("-");this.o=g.Eq(a,{hl:c});this.l=b;this.A=!!d;this.B={};this.g=null},s1=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.CD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.l=f;this.i=k},t1=function(a,b,c,d,e){g.CD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},v1=function(a){a=void 0===a?{}:a;
var b="_"+u1++;return new t1(0,0x8000000000000,0,b,a)},x1=function(a,b,c,d,e,f){var k={};
g.Xa(k,b);g.Xa(k,a.params);g.Xa(k,c);var l={};g.Xa(l,b.vb);a.params.vb&&g.Xa(l,a.params.vb);g.Xa(l,c.vb);k.vb=l;g.S.call(this,{C:"div",G:"caption-window",L:{id:"caption-window-"+a.id,dir:1==k.ng?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{C:"span",G:"captions-text"}]});this.u=[];this.Y=!1;this.o=a;this.F=[];this.N=[];this.Ra=e;this.Qa=f;this.B=this.I=null;this.Z=.96*e;this.xa=.96*f;this.l=k;this.La=c;this.A=this.i["captions-text"];this.Fa=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.X=d/360*16;this.type=0;this.la=this.X*w1(l);a=new g.ks(this.element,!0);g.G(this,a);a.subscribe("dragstart",this.eF,this);a.subscribe("dragmove",this.dF,this);a.subscribe("dragend",this.cF,this);this.wa=this.oa=0;b="";this.l.windowOpacity&&(a=f1(this.l.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");a={"background-color":b,display:!1===this.l.isVisible?"none":"","text-align":loa[this.l.textAlign]};this.Fa&&(a["border-radius"]=
b?this.la/8+"px":"");if(this.D=2==this.o.params.ng||3==this.o.params.ng)b=this.element,c="vertical-rl",1==this.l.gA&&(c="vertical-lr"),g.ce&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.Lh(b,"-o-writing-mode",c),g.Lh(b,"-webkit-writing-mode",c),g.Lh(b,"writing-mode",c),g.Lh(b,"text-orientation","upright"),3==this.o.params.ng&&(g.Lh(b,"text-orientation",""),g.Lh(b,"transform","rotate(180deg)"));g.Lh(this.element,a);switch(this.l.Ef){case 0:case 1:case 2:g.J(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.J(this.element,
"ytp-caption-window-bottom")}},w1=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},y1=function(a,b){var c={},d=b.background?b.background:a.l.vb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.vb.backgroundOpacity;d=f1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Fa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.la/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.X*w1(b)+"px";d=1;e=b.color||a.l.vb.color;if(b.color||null!=b.textOpacity)e=f1(e),d=null==b.textOpacity?a.l.vb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.vu&&(k=e=b.vu);var l=a.X/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),u=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=u;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.ar()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.vb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.He&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.Nl&&(c.visibility="hidden");return c},z1=function(a,b,c){a.Y=a.Y||!!c;
var d={};g.Xa(d,a.l.vb);g.Xa(d,c||b.i);g.Xa(d,a.La.vb);c=a.F[0];if(c&&d.background==c.background&&d.backgroundOpacity==c.backgroundOpacity&&!!d.Nl==!!c.Nl&&d.charEdgeStyle==c.charEdgeStyle){var e;for(e=0;e<a.F.length;e++)if(g.rc(d,a.F[e])){var f=a.N[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.ie("SPAN");g.Lh(f,y1(a,e));a.N[0].appendChild(f);e=1}a.N.length=e;a.F.length=e}else a.N.length=0,a.F.length=0,f=g.ie("SPAN"),g.Lh(f,y1(a,d)),a.A.appendChild(f);k=!d.Nl;e=(c=g.t(b.text))?b.text.split("\n"):
[b.text];for(var l=0;l<e.length;l++){var m=e[l];if(0<l||0==a.u.length||!b.l){if(0<l||0!=a.u.length){var n=g.ie("BR");f.appendChild(n)}k&&a.cp(f)}m&&(k?a.I:f).appendChild(c?g.je(m):m)}if(!c)for(k=b.text.querySelectorAll("RT".toString()),c=0;c<k.length;c++)g.Lh(k[c],y1(a,d)),g.Lh(k[c],"font-size","50%");a.F.push(d);a.N.push(f);a.u.push(b)},A1=function(){},C1=function(){this.o=this.i=this.mode=this.l=0;
this.u=new B1(this);this.A=new B1(this);this.g=[];this.clear()},moa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{al:a,
bl:b,result:0};a=D1[a];b=D1[b];if(a&128){if(!(b&128)&&0!=c.g&&c.i==b)return{al:a,bl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{al:a,bl:b,result:2};return{al:a,bl:b,result:3}},noa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.o&&a.reset(),a.u.g.clear(),a.A.g.clear()):(a.o=0,E1(a.u,b,c,d))},ooa=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.i=d.time;0==d.type?noa(a,d.ou,d.pu,b):1==d.type&&a.l&496&&E1(a.A,d.ou,d.pu,b)}a.g.length=0},F1=function(){this.g=0},G1=function(){this.i=this.l=this.g=0},H1=function(){this.timestamp=this.Ld=0},I1=function(a){this.l=[];
for(var b=0;15>=b;b++){this.l[b]=[];for(var c=0;32>=c;c++)this.l[b][c]=new H1}this.g=this.i=this.row=0;this.style=new F1;this.u=a;this.o=0},J1=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.u.i+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var u=a.l[m][q];
if(0!=u.Ld){0==c&&(c=m,d=q);n=String.fromCharCode(u.Ld);var x=u.timestamp;x<e&&(e=x);u.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==u.Ld||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.u(c,d,e,l,f)}else for(d=c=0,f=e=a.u.i+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.l[k][m],u=q.Ld,0!=u&&(0==c&&(c=k,d=m),n=String.fromCharCode(u),x=q.timestamp,x<=e&&(e=x),l+=n,q.reset()),32==m||0==u)l&&b.u(c,d,e,f,l),e=f,l="",d=c=0},toa=function(a,b){switch(a){case 0:return poa[(b&127)-32];
case 1:return qoa[b&15];case 2:return roa[b&31];case 3:return soa[b&31]}return 0},K1=function(a){return a.l[a.row][a.i]},L1=function(a,b,c){2<=b&&1<a.i&&(--a.i,K1(a).Ld=0);
var d=K1(a);d.timestamp=a.u.i+0;d.Ld=toa(b,c);32>a.i&&a.i++},M1=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.l[b+e][f].Mf(a.l[c+e][f])},N1=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.l[b+d][e].reset()},O1=function(a){a.row=0<a.g?a.g:1;
a.i=1;N1(a,0,15)},P1=function(a){this.o=a;
this.u=0;this.style=new F1;this.A=new I1(a);this.B=new I1(a);this.D=new I1(a);this.i=this.A;this.l=this.B;this.g=this.i},Q1=function(a,b,c){var d=a.i,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:J1(d,c),O1(a.i),O1(a.l),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.o.mode=1<<d.o;e?d.i=1:d.g!=b&&(d.g>b?(J1(d,c),N1(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},R1=function(a){a.style.set(1);
a.g=a.l;a.g.g=0;a.g.style=a.style;a.o.mode=1<<a.g.o},S1=function(a){a.style.set(4);
a.g=a.D;a.g.style=a.style;a.o.mode=1<<a.g.o},B1=function(a){this.i=a;
this.g=new G1;this.u=0;this.l=new P1(a);this.A=new P1(a);this.o=this.l},E1=function(a,b,c,d){a.g.update();
b=moa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.al;c=b.bl;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.o.g,b&96&&L1(a,0,b),c&96&&L1(a,0,c),0!=b&&0!=c&&3==a.style.g&&J1(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.l=e,b.i=c,b.g=2,b=e&8?a.A:a.l,a.o=b,a.i.mode=1<<(a.u<<2)+(b.u<<1)+(4==b.style.g?1:0),(a.i.mode|1<<(a.u<<2)+(b.u<<1)+(4!=b.style.g?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;M1(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));N1(c,b,e)}}c.row=d;c.i=a+1}else switch(e&7){case 1:switch(c&112){case 32:L1(b.g,0,32);break a;case 48:57==c?(b=b.g,K1(b).Ld=0,32>b.i&&b.i++):L1(b.g,1,c&15)}break;case 2:c&32&&L1(b.g,2,c&31);break;case 3:c&32&&L1(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:R1(b);break;case 33:b=
b.g;1<b.i&&(--b.i,K1(b).Ld=0);break;case 36:b=b.g;d=K1(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.l[a][c]==d){for(;32>=c;c++)b.l[a][c].reset();break}break;case 37:Q1(b,2,d);break;case 38:Q1(b,3,d);break;case 39:Q1(b,4,d);break;case 40:L1(b.g,0,32);break;case 41:b.style.set(2);b.g=b.i;b.g.g=0;b.g.style=b.style;b.o.mode=1<<b.g.o;break;case 42:d=b.D;d.g=15;d.style.set(4);O1(d);S1(b);break;case 43:S1(b);break;case 44:a=b.i;switch(b.style.get()){case 1:case 2:case 3:J1(a,d)}N1(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.i=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;J1(a,d);M1(a,b,b+1,a.g-1);N1(a,a.row,1)}break;case 46:N1(b.l,0,15);break;case 47:J1(b.i,d);d=b.l;a=b.o.i+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.l[c][e].timestamp=a;d=b.l;b.l=b.i;b.i=d;R1(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.i+=c&3)&&(b.i=32)}}},T1=function(a){g.E.apply(this,arguments)},U1=function(a){T1.call(this);
this.o={};this.F={};this.H={};this.u="_"+u1++;this.A=a;this.D={};this.i=this.g=null;this.B=!0},V1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},W1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},X1=function(a,b){var c=V1(a,b);
return void 0!=c?c:null},Z1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Y1.test(c),c},$1=function(a,b){var c={},d=b.getAttribute("ws");
g.Xa(c,d?a.H[d]:a.A);d=X1(b,"mh");null!=d&&(c.Gq=d);d=X1(b,"ju");null!=d&&(c.textAlign=d);d=X1(b,"pd");null!=d&&(c.ng=d);d=X1(b,"sd");null!=d&&(c.gA=d);d=Z1(b,"wfc");null!=d&&(c.windowColor=d);d=V1(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},a2=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Xa(c,a.F[d]);d=X1(b,"ap");null!=d&&(c.Ef=d);d=V1(b,"cc");null!=d&&(c.Au=d);d=V1(b,"ah");null!=d&&(c.Ie=d);d=V1(b,"rc");null!=d&&(c.Yr=d);d=V1(b,"av");null!=d&&(c.pg=d);return c},b2=function(a,b,c,d){var e={};
g.Xa(e,a2(a,b));g.Xa(e,$1(a,b));d?g.rc(e,a.A)?(d=a.u,e=a.A):d="_"+u1++:d=b.getAttribute("id")||"_"+u1++;a=V1(b,"t")+c;b=V1(b,"d")||0x8000000000000;return new t1(a,b,0,d,e)},c2=function(a,b,c,d,e,f,k){x1.call(this,a,b,c,d,e,f,k);
this.type=1},d2=function(a,b,c){this.B=c;
this.version=this.A=this.o=this.g=0;this.i=new DataView(a);this.l=[]},e2=function(a){var b=a.g;
a.g+=1;return a.i.getUint8(b)},f2=function(a){var b=a.g;
a.g+=4;return a.i.getUint32(b)},g2=function(a,b){T1.call(this);
this.i=a;this.track="CC3"==b.l?4:0;this.g=new C1;this.g.l=1<<this.track},i2=function(a){if(g.t(a))return!1;
a=new d2(a,8,0);return h2(a)},h2=function(a){if(!(a.g<a.i.byteLength)||1380139777!=f2(a))return!1;
a.version=e2(a);if(1<a.version)return!1;e2(a);e2(a);e2(a);return!0},j2=function(a,b,c,d,e,f,k){x1.call(this,a,b,c,d,e,f,k);
g.J(this.element,"ytp-caption-window-rollup");this.type=2;this.H=[];this.V=this.O=this.fa=0;this.T=NaN;this.za=0;this.Ga=null;this.ka=new g.L(this.QJ,433,this);g.G(this,this.ka)},uoa=function(a,b){return(a.D?b.offsetHeight:b.offsetWidth)+1},voa=function(a){if(isNaN(a.T)){var b=a.l.Au;
if(b){var c=g.ie("SPAN");g.se(c,"\u2013".repeat(b));g.Lh(c,y1(a,a.l.vb));a.A.appendChild(c);a.T=c.offsetWidth;a.A.removeChild(c)}else a.T=0}return a.T},woa=function(a,b){if(!b)return"";
a.D&&1!=a.o.params.gA&&(b*=-1);return"translate"+(a.D?"X":"Y")+"("+b+"px)"},k2=function(a){a.H=Array.prototype.slice.call(g.Vd("ytp-rollup-caption-line-wrapper"));
for(var b=a.o.params.Yr,c=0,d=0,e=a.H.length-1;c<b&&-1<e;){var f=a.H[e];d+=a.D?f.offsetWidth:f.offsetHeight;c++;e--}a.H.length<b&&(d*=b/a.H.length);a.O=d;a.V=Math.max(voa(a),a.za,uoa(a,a.A))},xoa=function(a,b){k2(a);
var c=a.H.reduce(function(b,c){return(a.D?c.offsetWidth:c.offsetHeight)+b},0);
c=a.O-c;if(c!=a.fa){var d=0<c&&0==a.fa;b||isNaN(c)||d||(g.J(a.element,"ytp-rollup-mode"),g.Do(a.ka));g.Lh(a.A,"transform",woa(a,c));a.fa=c}k2(a)},l2=function(){T1.call(this)},m2=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.He=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType){q=new s1(b,c,d,e.id,q.nodeValue,f||0<n,g.nc(l)?void 0:l);m.push(q);var u=e;g.G(u,q);u.i.push(q)}else u={},g.Xa(u,l),m2(a,b,c,d,e,!0,q,u,m)}},n2=function(a){var b=0;
a=g.p(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},o2=function(a,b,c,d){d=Object.assign({Gq:0},d);
return new t1(a,b,c,"_"+u1++,d)},p2=function(a){g.E.call(this);
this.i=a;this.g=null},s2=function(a){g.fK.call(this,a);
this.u=g.V(a);this.l=a.getVideoData();this.wa=g.DJ(a);this.I=a;var b=null,c=g.op("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Zo(c));this.aa=b;this.o={vb:{}};this.A={vb:{}};this.H=[];this.N={};this.T={};this.P=!1;this.la=g.mU(this.l,this.I);this.xa=!!this.l.captionTracks.length;this.za=!!this.l.Zi;this.ka="3"==this.u.o;b=a.app.o;c=!(!b||!b.Ck());this.oa=!(!b||!b.mh());this.B=this.ka&&c&&!this.la;this.V=!this.B&&this.ka&&this.oa&&this.la;this.i=this.D=this.F=this.O=this.fa=null;this.Y=
new p2(this.u);g.G(this,this.Y);c=b=this.g=null;this.B||(b=new g.Ao(this.xA,void 0,this),g.G(this,b),c=new g.L(this.oL,2E3,this),g.G(this,c));this.X=b;this.Z=c;this.ba=new g.es(this);g.G(this,this.ba);this.B||this.ba.K(a,"resize",this.Ns);this.ba.K(a,"onPlaybackAudioChange",this.kH);this.ba.K(a,g.FD("captions"),this.oE,this);this.ba.K(a,"crx_captions",this.pE,this);q2(this,r2(this,"display-settings")||{})},t2=function(a){if(1==a.u.If||1==a.l.If||"alwayson"==g.vB(a.l,"yt:cc"))return!0;
if(2==a.u.If){var b=r2(a,"module-enabled");if(null!=b)return!!b}if(a.l.captionTracks.length)var c=a.player.getAudioTrack().Qo;return"ON"==c||"on"==g.vB(a.l,"yt:cc")},u2=function(a,b){if(a.g&&(void 0===b||!b)||!a.l.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.zl||"FORCED_ON"==c.Qo},w2=function(a,b){if(a.i){if(a.D&&a.D.g)return a.D.g;
var c=b;c||(c=a.za?!1:a.xa?!1:!0);c=g1(a.i.i,c);for(var d=[a.l.Hf,a.u.Hf,g.vB(a.l,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(e1(c[f])==d[e])return c[f];return a.D&&a.D.fp?a.D.fp:(d=c.find(function(a){return a.isDefault}))?d:c[0]||v2(a)}return null},v2=function(a){return a.D&&a.D.zl},x2=function(a){var b=v2(a);
return!!b&&a.g==b},y2=function(a,b){for(var c=a.I.app.o.ha().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},A2=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.P=c,a.P&&z2(a,"module-enabled",!!b));a.g=b;u2(a)&&(a.g=v2(a));a.load()},yoa=function(a,b){var c=a.wa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.wa.getPlayerSize();switch(null!=b.params.Gq?b.params.Gq:1<b.i.length?1:0){case 1:return new c2(b,a.o,a.A,c,d.width,d.height,a.u.experiments);case 2:return new j2(b,a.o,a.A,c,d.width,d.height,a.u.experiments);default:return new x1(b,a.o,a.A,c,d.width,d.height,a.u.experiments)}},q2=function(a,b,c){var d=B2.vb;
a.o={};g.Xa(a.o,B2);a.o.vb={};g.Xa(a.o.vb,d);a.A={vb:{}};var e=b.backgroundOverride?a.A:a.o,f=b.background||d.background;Y1.test(f);e.vb.background=f;e=b.colorOverride?a.A:a.o;f=b.color||d.color;Y1.test(f);e.vb.color=f;e=b.windowColorOverride?a.A:a.o;f=b.windowColor||B2.windowColor;Y1.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.A:a.o;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.vb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.A:a.o;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.vb.fontSizeIncrement=f;f=b.fontStyleOverride?a.A:a.o;e=b.fontStyle;null==e&&(e=d.bold&&d.He?3:d.bold?1:d.He?2:0);f=f.vb;switch(e){case 1:f.bold=!0;delete f.He;break;case 2:delete f.bold;f.He=!0;break;case 3:f.bold=!0;f.He=!0;break;default:delete f.bold,delete f.He}e=b.textOpacityOverride?a.A:a.o;f=b.textOpacity;null==f&&(f=d.textOpacity);e.vb.textOpacity=f;e=b.windowOpacityOverride?a.A:a.o;f=b.windowOpacity;null==f&&(f=B2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.A:a.o;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.vb.charEdgeStyle=f;e=b.fontFamilyOverride?a.A:a.o;f=b.fontFamily;null==f&&(f=d.fontFamily);e.vb.fontFamily=f;a.loaded&&a.Ns();c&&z2(a,"display-settings",b)},D2=function(a,b){if(b&&!a.F){var c=v1({ng:0,
lang:"es-419"});a.F=[c,new s1(c.start,c.end-c.start,0,c.id,"Los subt\u00edtulos tendr\u00e1n este aspecto:")];g.MJ(a.player,a.F)}else!b&&a.F&&(C2(a,a.F),a.F=null)},C2=function(a,b){g.OJ(a.player,b);
(0,g.A)(b,function(a){g.nb(this.H,a)},a);
a.X.yj()},r2=function(a,b){if(!a.aa)return null;
try{var c=a.aa.get(b)}catch(d){a.aa.remove(b)}return c},z2=function(a,b,c){if(a.aa)try{a.aa.set(b,c)}catch(d){}};
g.OD.prototype.bj=g.ca(13,function(){for(var a=g.Ud(document,"track",void 0,this.g),b=0;b<a.length;b++)g.ne(a[b])});
g.fW.prototype.bj=g.ca(12,function(){this.g.bj()});
g.OD.prototype.Ck=g.ca(11,function(){return!!this.g.textTracks});
g.fW.prototype.Ck=g.ca(10,function(){return this.g.Ck()});
g.OD.prototype.Ui=g.ca(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.fW.prototype.Ui=g.ca(8,function(a){this.g.Ui(a)});
g.EC.prototype.mh=g.ca(7,function(){});
g.OD.prototype.mh=g.ca(6,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.fW.prototype.mh=g.ca(5,function(){return this.g.mh()});
g.sz.prototype.Nq=g.ca(3,function(a){return a?this.toString()==a.toString():!1});
g.Bt.prototype.Il=g.ca(2,function(a){return(a=this.Rf(a))?a.i:0});
g.uw.prototype.Il=g.ca(1,function(){return 0});
var zoa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,ioa=/#(.)(.)(.)/,hoa=/^#(?:[0-9a-f]{3}){1,2}$/i,Y1=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(i1,g.E);i1.prototype.ez=function(){return!1};
i1.prototype.R=function(){this.qg();g.E.prototype.R.call(this)};
g.r(j1,i1);j1.prototype.Cq=function(a,b,c){b=this.uj(a,b);var d=(0,g.y)(function(b){this.g=null;c(b.responseText,a)},this);
this.qg();this.g=g.Sq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
j1.prototype.Dq=function(a){if(this.l)for(var b=g.p(this.l.captionTracks),c=b.next();!c.done;c=b.next())h1(this.i,c.value);a()};
j1.prototype.uj=function(a,b){var c=a.Eb(),d={fmt:b};a.g&&(d.tlang=e1(a));return g.Eq(c,d)};
j1.prototype.qg=function(){this.g&&this.g.abort()};
k1.prototype.contains=function(a){a=g.zb(this.Ta,a);return 0<=a||0>a&&1==(-a-1)%2};
k1.prototype.length=function(){return this.Ta.length/2};
g.r(l1,g.E);g.h=l1.prototype;g.h.R=function(){g.E.prototype.R.call(this);this.i&&this.i.cancel()};
g.h.kx=function(a){var b=this;if(this.D.Mg())var c=this.u.K(this.o,"progresssync",function(){b.D.index.Kb()&&(b.reset(),b.g=null,m1(b,b.o.getCurrentTime()),b.u.Na(c))});
else m1(this,a)};
g.h.fF=function(){m1(this,this.o.getCurrentTime())};
g.h.reset=function(){this.A=new k1;this.i&&(this.i.cancel(),this.i=null)};
g.h.Bw=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.vf(a);!a||this.i||this.g&&30<this.g.startTime-this.o.getCurrentTime()||(a=this.g,a=a.g.Yh(a),a.g[0].duration&&(this.A.contains(a.g[0].i)||n1(this,a),this.g=g.ab(a.g)));this.H.start()};
g.h.LJ=function(a){var b=!(this.B?a.response:a.responseText)||400<=a.status,c=g.Bw(a);c?(a=g.Kv(this.l,this.I,{}),b=this.l,g.Fv(b.i,a,c),b.requestId=a.get("req_id"),n1(this,this.l)):(b||null===this.F||(this.B?this.F(a.response,1E3*(this.l.g[0].startTime+this.o.hc())):this.F(a.responseText,1E3*(this.l.g[0].startTime+this.o.hc()))),this.i=this.l=null)};
g.r(o1,i1);g.h=o1.prototype;g.h.Cq=function(a,b,c){this.qg();b=koa(this,a.getId());b||(b=a.i,b=this.g.i?q1(this,b,"386"):q1(this,b));if(b){var d=1E3*(b.index.Il(b.index.fe())-b.index.Ec(b.index.fe()));this.l=new l1(new g.$u,this.B,b,function(b,f){c(b,a,f,d)},this.A||g.Tu(b.info),(0,g.y)(function(){this.l&&this.l.reset();
this.o=!0},this))}};
g.h.ez=function(){var a=this.o;this.o=!1;return a};
g.h.Dq=function(a){var b;this.A?b=[new g.sz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.sz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.g.i?p1(this,"386"):p1(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())h1(this.i,c.value);a()};
g.h.qg=function(){this.l&&(this.l.dispose(),this.l=null)};
g.h.uj=function(){return""};
g.r(r1,i1);r1.prototype.Cq=function(a,b,c){b=this.uj(a,b);var d=(0,g.y)(function(b){this.g=null;c(b.responseText,a)},this);
this.qg();this.g=g.Sq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
r1.prototype.Dq=function(a){var b=this.o,c={type:"list",tlangs:1,v:this.l,vssids:1};this.A&&(c.asrs=1);b=g.Eq(b,c);c=(0,g.y)(function(b){this.g=null;if((b=b.responseXML)&&b.firstChild){for(var c=g.p(b.getElementsByTagName("track")),d=c.next();!d.done;d=c.next()){var k=d.value;d=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),q=k.getAttribute("id"),u="true"==k.getAttribute("lang_default"),x="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
h1(this.i,new g.sz({languageCode:d,languageName:l,name:m,kind:n,id:q,is_servable:!0,is_translateable:x,vss_id:k,is_default:u}))}b=b.getElementsByTagName("target");c=b.length;for(d=0;d<c;d++)l=b[d].getAttribute("lang_code"),m=b[d].getAttribute("lang_translated"),n=b[d].getAttribute("lang_original"),q=b[d].getAttribute("id"),u="true"==b[d].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:q,isDefault:u},this.B[l.languageCode]=l.languageName,this.u.push(l)}a()},this);
this.qg();this.g=g.Sq(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
r1.prototype.uj=function(a,b){var c=this.o,d={v:this.l,type:"track",lang:a.i,name:a.u,kind:a.o,fmt:b};a.g&&(d.tlang=e1(a));return c=g.Eq(c,d)};
r1.prototype.qg=function(){this.g&&this.g.abort()};var loa=["left","right","center","justify"];var B2={windowColor:"#080808",windowOpacity:0,textAlign:2,Ef:7,Ie:50,pg:100,vb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(s1,g.CD);s1.prototype.toString=function(){return g.CD.prototype.toString.call(this)};g.r(t1,g.CD);t1.prototype.toString=function(){return g.CD.prototype.toString.call(this)};
var u1=0;g.r(x1,g.S);g.h=x1.prototype;g.h.eF=function(a,b){var c=g.ai(this.element,this.element.parentElement);this.oa=a-c.x;this.wa=b-c.y;g.J(this.element,"ytp-dragging")};
g.h.dF=function(a,b){var c=g.di(this.element),d=a-this.oa-.02*this.Ra,e=b-this.wa-.02*this.Qa,f=(d+c.width/2)/this.Z*3;f=Math.floor(g.Fd(f,0,2));var k=(e+c.height/2)/this.xa*3;k=Math.floor(g.Fd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.Z;d=100*g.Fd(d,0,1);c=(e+k/2*c.height)/this.xa;c=100*g.Fd(c,0,1);this.o.params.Ef=l;this.o.params.pg=c;this.o.params.Ie=d;this.l.Ef=l;this.l.pg=c;this.l.Ie=d;this.zz()};
g.h.cF=function(){g.uo(this.element,"ytp-dragging")};
g.h.zz=function(){this.ih(this.u)};
g.h.ih=function(a){var b=Math.min(this.Cv(),this.Z),c=this.Bv(),d="";3==this.o.params.ng&&(d="rotate(180deg)");g.Lh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Eo(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.l.Ie+2;d=this.l.Ef;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.A.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.l.pg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Lh(this.element,a)};
g.h.Eo=function(a){var b;for(b=0;b<a.length&&a[b]==this.u[b];b++);if(this.Y||this.u.length>b)b=0,this.Y=!1,this.u=[],this.F=[],this.N=[],this.I=this.B=null,g.le(this.A);for(;b<a.length;b++)z1(this,a[b])};
g.h.Cv=function(){return 0};
g.h.Bv=function(){return 0};
g.h.cp=function(a){this.B=g.ie("SPAN");this.B.appendChild(g.je("\u00a0"));this.I=g.ie("SPAN");g.J(this.I,"caption-visual-line");this.B.appendChild(this.I);this.B.appendChild(g.je("\u00a0"));a.appendChild(this.B)};
g.h.toString=function(){return g.S.prototype.toString.call(this)};A1.prototype.u=function(){};C1.prototype.clear=function(){this.o=this.i=this.mode=0;this.g=[];this.reset()};
C1.prototype.reset=function(){this.mode=0;this.u.reset(0);this.A.reset(1)};
var D1=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];F1.prototype.set=function(a){this.g=a};
F1.prototype.get=function(){return this.g};
G1.prototype.clear=function(){this.g=0};
G1.prototype.update=function(){this.g=2==this.g?1:0};
G1.prototype.matches=function(a,b){return 0!=this.g&&a==this.l&&b==this.i};
H1.prototype.Mf=function(a){this.Ld=a.Ld;this.timestamp=a.timestamp};
H1.prototype.reset=function(){this.timestamp=this.Ld=0};
I1.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.l[b][c];a=0==d.Ld?a+"_":a+String.fromCharCode(d.Ld)}a+="\n"}return a};
I1.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.l[b][c].reset();this.o=a;this.g=0;this.i=this.row=1};
var poa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],qoa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],roa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],soa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];P1.prototype.reset=function(a,b){this.u=b;this.style.set(2);this.i=this.A;this.l=this.B;this.g=this.i;var c=(a<<2)+(b<<1);this.A.reset(c);this.B.reset(c);this.D.reset((a<<2)+(b<<1)+1)};
B1.prototype.reset=function(a){this.u=a;this.g.clear();this.o=this.l;this.l.reset(a,0);this.A.reset(a,1)};g.r(T1,g.E);T1.prototype.reset=function(){};g.r(U1,T1);U1.prototype.reset=function(){this.D={};this.i=this.g=null;this.B=!0};
U1.prototype.l=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.o,l={},m=c.getAttribute("p");m&&g.Xa(l,this.o[m]);m=W1(c,"b");null!=m&&(l.bold=
m);m=W1(c,"i");null!=m&&(l.He=m);m=W1(c,"u");null!=m&&(l.underline=m);m=X1(c,"et");null!=m&&(l.charEdgeStyle=m);m=X1(c,"of");null!=m&&(l.offset=m);m=Z1(c,"bc");null!=m&&(l.background=m);m=Z1(c,"ec");null!=m&&(l.vu=m);m=Z1(c,"fc");null!=m&&(l.color=m);m=X1(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=V1(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=V1(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=V1(c,"fo");void 0!=m&&(l.textOpacity=m/255);c=X1(c,"rb");null!=c&&(l.tL=c);k[d]=l;break;case "ws":d=
c.getAttribute("id");this.H[d]=$1(this,c);break;case "wp":d=c.getAttribute("id"),this.F[d]=a2(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=b2(this,d,e,!1);g.G(this,this.g);(d=this.D[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.D[this.g.id]=this.g;c.push(this.g);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.u;m=!!W1(d,"a");n=(V1(d,"t")||0)+n;var q=V1(d,"d")||5E3;m||(!this.B&&
this.i&&this.i.windowId==l&&this.i.end>n&&(this.i.end=n),this.i&&"\n"==this.i.text&&(this.i.text=""));var u=m?6:5,x=this.o[d.getAttribute("p")],C=d.childNodes;C.length&&(this.B=null!=d.getAttribute("d"));for(var F=0;F<C.length;F++){var H=C[F];0<F&&(m=!0);var T=void 0;1==H.nodeType&&(T=H);if(T&&"s"==T.tagName)if((H=this.o[T.getAttribute("p")])&&1==H.tL){H=n;var X=q,ra=l,wb=m,Gb=u;var Mc=T;var ag=C[F+1],Dh=C[F+2],Cc=C[F+3];Mc.getAttribute("p");V1(Mc,"t");V1(ag,"t");V1(Dh,"t");V1(Cc,"t");T=g.ie("RUBY");
Mc=Mc.textContent;var Mk=g.ie("SPAN");Mk.innerText=Mc;T.appendChild(Mk);ag.getAttribute("p");Mk=g.ie("RP");Mc=ag.textContent;Mk.innerText=Mc;T.appendChild(Mk);Dh.getAttribute("p");Mc=Dh.textContent;ag=g.ie("RT");ag.innerText=Mc;T.appendChild(ag);Cc.getAttribute("p");Mc=Cc.textContent;Cc=g.ie("RP");Cc.innerText=Mc;T.appendChild(Cc);H=new s1(H,X,Gb,ra,T,wb,null);F+=3}else Cc=T,H=n,X=q,ra=l,wb=m,Gb=u,T=Cc.textContent?Cc.textContent:"",Mc=this.o[Cc.getAttribute("p")],Cc=V1(Cc,"t")||0,H=new s1(H+Cc,X-
Cc,Gb,ra,T,wb,Mc);else H=new s1(n,q,u,l,H.textContent||"",m,x);k.push(H);this.i=H}if(0<k.length)for(k[0].windowId==this.u&&(this.g=b2(this,d,e,!0),g.G(this,this.g),c.push(this.g)),d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.G(l,k),l.i.push(k),c.push(k)}e=c}else e=[];return e};g.r(c2,x1);c2.prototype.Eo=function(a){var b=this.o.i;x1.prototype.Eo.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i==e)var d=f;else{d={};g.Xa(d,c.i);g.Xa(d,Aoa);var e=c.i;var f=d}z1(this,c,d)}};
var Aoa={Nl:!0};g.r(d2,A1);d2.prototype.u=function(a,b,c,d,e){if(c<d){var f="_"+u1++;c=c/1E3-this.B;d=d/1E3-this.B;a=new t1(c,d-c,5,f,{textAlign:0,Ef:0,Ie:2.5*b,pg:5.33*a});e=new s1(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.r(g2,T1);g2.prototype.l=function(a){a=new d2(a,a.byteLength,this.i);if(h2(a)){for(;a.g<a.i.byteLength;)for(0==a.version?a.o=f2(a)*(1E3/45):1==a.version&&(a.o=4294967296*f2(a)+f2(a)),a.A=e2(a);0<a.A;a.A--){var b=e2(a),c=e2(a),d=e2(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.o,type:this.track,ou:c,pu:d,order:b.g.length}))}ooa(this.g,a);return a.l}return[]};
g2.prototype.reset=function(){this.g.clear()};g.r(j2,x1);g.h=j2.prototype;g.h.zz=function(){g.Eo(this.ka)};
g.h.QJ=function(){g.uo(this.element,"ytp-rollup-mode");this.ih(this.Ga,!0)};
g.h.Bv=function(){return this.D?this.V:this.O};
g.h.Cv=function(){return this.D?this.O:this.V};
g.h.cp=function(a){x1.prototype.cp.call(this,a);g.J(this.B,"ytp-rollup-caption-line-wrapper");g.Lh(this.B,"display","inline-block");g.Lh(this.I,"display","inline-block")};
g.h.ih=function(a,b){this.Ga=a;if(this.o.params.Yr){for(var c=0,d=0;d<this.u.length&&c<a.length;d++)this.u[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.u.concat(a.slice(c)));this.za=this.V;this.O=this.V=0;x1.prototype.ih.call(this,a);xoa(this,b);x1.prototype.ih.call(this,a)}else x1.prototype.ih.call(this,a)};g.r(l2,T1);
l2.prototype.l=function(a,b){for(var c=[],d=a.split(Boa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Coa.test(f)){var l=E2.exec(f);if(l&&4<=l.length){var m=n2(l[1]),n=n2(l[2])-m;m+=k;var q,u=q=void 0,x=void 0,C=void 0,F=l[3];l={textAlign:2};F=g.p(F?F.split(" "):[]);for(var H=F.next();!H.done;H=F.next())if(H=H.value.split(":"),2==H.length){var T=H[1];switch(H[0]){case "line":H=T.split(",");H[0].endsWith("%")&&(C=H[0],l.pg=Number.parseInt(C,10),2==H.length&&(x=H[1].trim()));break;case "position":H=T.split(",");
u=H[0];l.Ie=Number.parseInt(u,10);2==H.length&&(q=H[1].trim());break;case "align":switch(T){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}C||(l.pg=100,x||(x="end"));if(!u)switch(l.textAlign){case 0:l.Ie=0;break;case 1:l.Ie=100;break;default:l.Ie=50}u=0;switch(x){case "center":u+=3;break;case "end":u+=6;break;default:u+=0}switch(q){case "line-left":u+=0;break;case "center":u+=1;break;case "line-right":u+=2;break;default:switch(l.textAlign){case 0:u+=
0;break;case 2:u+=1;break;case 1:u+=2}}l.Ef=0>u||8<u?7:u;q=l;f=f.substring(E2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=q;q=f;f={};if(0>q.indexOf("<")&&0>q.indexOf("&"))k=o2(m,n,5,u),n=new s1(m,n,5,k.id,q,!1,g.nc(f)?void 0:f),c.push(k),c.push(n),g.G(k,n),k.i.push(n);else for(x=q.split(Doa),1==x.length?(q=5,u=o2(m,n,q,u)):(C=q=6,u=Object.assign({Au:32},u),u=new t1(m,n,C,"_"+u1++,u)),c.push(u),C=m,l=0;l<x.length;l++)F=x[l],0==l%2?(H=g.wo("<html>"+F+"</html>"),H.getElementsByTagName("parsererror").length?
(T=H.createElement("span"),T.appendChild(H.createTextNode(F))):T=H.firstChild,m2(this,C,n-(C-m),q,u,0<l,T,f,c)):C=n2(F)+k}E2.lastIndex=0}}return c};
var Coa=/^NOTE/,Boa=/(?:\r\n|\r|\n){2,}/,E2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Doa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(p2,g.E);p2.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
p2.prototype.reset=function(){this.g&&this.g.reset()};
p2.prototype.R=function(){this.clear();g.E.prototype.R.call(this)};g.r(s2,g.fK);g.h=s2.prototype;g.h.R=function(){if(this.B||this.V){var a=this.I.app.o;a&&a.bj()}else D2(this,!1);g.fK.prototype.R.call(this)};
g.h.xk=function(){return this.ka?this.B||this.V:u2(this)?!0:t2(this)};
g.h.load=function(){g.fK.prototype.load.call(this);this.D=this.player.getAudioTrack();if(this.i)this.g&&(this.Y.clear(),this.B?y2(this,!0):3!=this.player.getPresentingPlayerType()&&this.i.Cq(this.g,"srv3",(0,g.y)(this.xK,this))),this.g&&!x2(this)?this.player.ma("captionschanged",d1(this.g)):this.player.ma("onCaptionsTrackListChanged");else{var a;this.la?a=new o1(this.l.ia,this.player):this.xa?a=new j1(this.u,this.l,this.player.getAudioTrack()):a=new r1(this.l.Zi,this.l.videoId,this.l.Hf||this.u.Hf||
g.vB(this.l,"yt:cc_default_lang")||this.u.zc,this.l.Oo,this.u);this.i=a;g.G(this,this.i);a.Dq((0,g.y)(this.wK,this))}};
g.h.unload=function(){this.B&&this.g?y2(this,!1):(this.Z&&g.Fo(this.Z),g.PJ(this.player,"captions"),this.H=[],this.i&&this.i.qg(),this.Y.clear(),this.F&&g.MJ(this.player,this.F),this.Ns());g.fK.prototype.unload.call(this);var a=g.W(this.player.app);a&&a.o&&g.sC(a.o.l);this.player.ma("captionschanged",{})};
g.h.wK=function(){var a;this.P||t2(this)?a=w2(this,this.P):u2(this)&&(a=v2(this));if(this.B||this.V){for(var b=g1(this.i.i,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.tz(e),srclang:e1(e),id:e.toString()};this.V||(f.src=this.i.uj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.he("TRACK",f))}this.I.app.o.Ui(c);a=this.I.app.o.ha();this.oa&&this.ba.K(a.textTracks,"change",this.yK)}else!this.g&&a&&A2(this,a),this.player.ma("onCaptionsTrackListChanged"),this.player.ma("onApiChange")};
g.h.yK=function(){for(var a=this.I.app.o.ha().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=g1(this.i.i,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.g:null)!=b&&A2(this,b,!0)};
g.h.TL=function(){!this.g&&this.B||this.unload()};
g.h.xK=function(a,b,c,d){if(a){this.i.ez()&&(this.H=[],g.PJ(this.I,"captions"),this.X.yj(),this.Y.reset());var e=this.Y;c=c||0;d=d||0;if(!g.t(a)){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.Wt(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!i2(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=
a[k++];var q=a[k++],u=a[k++];m=((m&7)<<18|(n&63)<<12|(q&63)<<6|u&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],q=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|q&63)}a=f.join("")}}if(a)try{if(g.t(a)){if("WEBVTT"==a.substring(0,6)){b=a;var x=c;e.g||(e.g=new l2);var C=e.g.l(b,x);.01>Math.random()&&g.Zp(Error("Deprecated subtitles format in web player: WebVTT"));var F=C}else b:{C=a;x=g.wo(C);if(!x||!x.firstChild)throw Error("Invalid caption track data: "+
C);if("timedtext"==x.firstChild.tagName){if(3==parseInt(x.firstChild.getAttribute("format"),10)){if(!e.g){C={};var H=e1(b);H&&(C.lang=H,zoa.test(H)&&(C.ng=1));e.g=new U1(C,e.i)}F=e.g.l(x,c);break b}var T=Error("Unsupported subtitles format in web player (Format2)");T.params=C;throw T;}if("transcript"==x.firstChild.tagName)throw Error("Unsupported subtitles format in web player (Format1): "+C);throw Error("Invalid caption track data: "+C);}var X=F}else{F=a;x=c;H=d;if(!i2(F))throw Error("Invalid binary caption track data");
e.g||(e.g=new g2(H,b));X=e.g.l(F,x)}var ra=X}catch(wb){g.M(wb),e.clear(),ra=[]}else ra=[];g.MJ(this.player,ra);!this.P||this.V||x2(this)||g.Uy(this.u)||g.Vy(this.u)||(g.Fo(this.Z),ra=v1({Ef:0,Ie:5,pg:5,Yr:2,textAlign:0,ng:0,lang:"es-419"}),this.O=[ra],e=["Haz clic en "," para acceder a la configuraci\u00f3n."],this.fa||(X=new g.UB(g.eP()),g.G(this,X),this.fa=X.element),X=ra.end-ra.start,(b=g.tz(this.g))&&this.O.push(new s1(ra.start,X,0,ra.id,b)),this.O.push(new s1(ra.start,X,0,ra.id,e[0]),new s1(ra.start,
X,0,ra.id,this.fa,!0),new s1(ra.start,X,0,ra.id,e[1],!0)),g.MJ(this.player,this.O),g.Do(this.Z));!this.P||this.V||x2(this)||(z2(this,"module-enabled",!0),this.D&&(this.D.g=this.g),(ra=g.W(this.player.app))&&ra.o&&g.sC(ra.o.l));this.P=!1}};
g.h.oE=function(a){this.H.push(a);this.X.yj()};
g.h.pE=function(a){g.nb(this.H,a);this.i instanceof o1&&this.i.A&&g.OJ(this.player,[a]);this.X.yj()};
g.h.iL=function(a){if(a instanceof t1){var b=this.N[a.id];b&&b.o!=a&&(b.dispose(),delete this.N[a.id],b=null);b||(b=yoa(this,a))&&(this.N[a.id]=b)}else b=a.windowId,this.T[b]||(this.T[b]=[]),this.T[b].push(a)};
g.h.oL=function(){C2(this,this.O);this.O=null};
g.h.xA=function(){this.X.stop();g.oc(this.T);this.H.sort(g.ED);var a=this.H;if(this.F){var b=(0,g.oe)(a,function(a){return-1==this.F.indexOf(a)},this);
b.length&&(a=b)}(0,g.A)(a,this.iL,this);g.ac(this.N,function(a,b){this.T[b]?(a.element.parentNode||g.TJ(this.player,a.element,4),a.ih(this.T[b])):(a.dispose(),delete this.N[b])},this)};
g.h.sL=function(){q2(this,{},!0)};
g.h.xC=function(){var a=B2.vb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.He?3:a.bold?1:a.He?2:0,textOpacity:a.textOpacity,windowColor:B2.windowColor,windowOpacity:B2.windowOpacity};var b=r2(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.CA=function(a,b){var c={};g.Xa(c,r2(this,"display-settings"));g.Xa(c,a);q2(this,c,b);this.player.M("captionssettingschanged")};
g.h.Ns=function(){!this.B&&this.loaded&&(g.ac(this.N,function(a,b){a.dispose();delete this.N[b]},this),this.xA())};
g.h.Vb=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Fd(b,-2,4);this.CA({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&A2(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.u.ub&&z2(this,"module-enabled",!!b);break;case "track":if(!this.i)return{};if(b){if(this.B)break;if(!g.Qa(b))break;if(g.nc(b)){A2(this,null,!0);break}for(var d=g1(this.i.i,!0),e=0;e<d.length;e++){var f=d[e];f.i!=b.languageCode||c&&f.l!=b.languageName||(c=b.translationLanguage?goa(f,b.translationLanguage):
f)}!c||c==this.g&&this.loaded||A2(this,c,!0)}else return this.loaded&&this.g&&!x2(this)?d1(this.g):{};return"";case "tracklist":return this.i?(0,g.D)(g1(this.i.i,!(!b||!b.includeAsr)),function(a){return d1(a)}):[];
case "translationLanguages":return this.i?this.i.u:[];case "sampleSubtitles":this.B||void 0==b||D2(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.u.ub&&a.push("stickyLoading");return a};
g.h.wj=function(){var a=this.g;return a?{cc:a.A}:{}};
g.h.oA=function(){this.loaded&&this.g&&!x2(this)?(z2(this,"module-enabled",!1),this.unload(),u2(this,!0)&&A2(this,v2(this),!1)):A2(this,x2(this)||!this.g?w2(this,!0):this.g,!0)};
g.h.kH=function(){var a=x2(this);u2(this,a)?A2(this,this.player.getAudioTrack().zl,!1):this.l.captionTracks.length&&(this.loaded&&this.unload(),this.xk()&&(a?A2(this,w2(this),!1):this.load()))};g.sU.captions=s2;})(_yt_player);
