(function(g){var window=this;var Loa=function(a,b){return g.kc(a,b)},$3=function(){},Moa=function(a){if(a.uc&&"function"==typeof a.uc)return a.uc();
if(g.t(a))return a.split("");if(g.Oa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.gc(a)},Noa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Oa(a)||g.t(a))(0,g.A)(a,b,void 0);else{if(a.Ed&&"function"==typeof a.Ed)var c=a.Ed();else if(a.uc&&"function"==typeof a.uc)c=void 0;else if(g.Oa(a)||g.t(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.hc(a);d=Moa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},a4=function(a){g.vn(a,"zx",g.Jc());
return a},b4=function(a,b,c){g.Na(c)||(c=[String(c)]);
g.An(a.l,b,c)},c4=function(a){return(a=g.Qo(a))?new ActiveXObject(a):new XMLHttpRequest},d4=function(a,b){return b+" ["+a.aa+" "+a.F+" "+a.getStatus()+"]"},Ooa=function(a){return"content-type"==a.toLowerCase()},e4=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.B&&(g.v.clearTimeout(a.B),a.B=null)},Poa=function(a){return g.ce&&g.Vc(9)&&g.Ia(a.timeout)&&g.Ga(a.ontimeout)},f4=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},g4=function(a,b){if(a.g){e4(a);
var c=a.g,d=a.P[0]?g.Ka:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},h4=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;f4(a);g4(a)},i4=function(a){return a.g?a.g.readyState:0},j4=function(a){if(a.i&&"undefined"!=typeof g.KX)if(a.P[1]&&4==i4(a)&&2==a.getStatus())d4(a,"Local request error detected and ignored");
else if(a.D&&4==i4(a))g.Sg(a.Rv,0,a);else if(a.dispatchEvent("readystatechange"),4==i4(a)){d4(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.bh(String(a.F))[1]||null;if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!Qoa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<i4(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";f4(a)}}finally{g4(a)}}},k4=function(a){g.eg.call(this);
this.headers=new g.jn;this.N=a||null;this.i=!1;this.P=this.g=null;this.aa=this.F="";this.u=0;this.l="";this.o=this.T=this.D=this.O=!1;this.A=0;this.B=null;this.Y="";this.I=this.V=!1},l4=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},Roa=function(a,b){var c=[];
g.jl(b,function(a){try{var b=g.ep.prototype.i.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ga(b)?g.dp(b)&&c.push(a):c.push(a)},a);
return c},Soa=function(a,b){var c=Roa(a,b);
(0,g.A)(c,function(a){g.ep.prototype.remove.call(this,a)},a)},m4=function(a){if(a.Zc){if(a.Zc.locationOverrideToken)return{locationOverrideToken:a.Zc.locationOverrideToken};
if(null!=a.Zc.latitudeE7&&null!=a.Zc.longitudeE7)return{latitudeE7:a.Zc.latitudeE7,longitudeE7:a.Zc.longitudeE7}}return null},Toa=function(a,b){g.jb(a,b)||a.push(b)},n4=function(a){var b=0,c;
for(c in a)b++;return b},Uoa=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))},Voa=function(a){try{return g.v.JSON.parse(a)}catch(d){var b=d}a=String(a);
if(Uoa(a))try{var c=eval("("+a+")");b&&(0,g.KW)("Invalid JSON: "+a,b);return c}catch(d){}throw Error("Invalid JSON string: "+a);},Woa=function(a,b,c,d){var e=new g.mn(null,void 0);
a&&g.nn(e,a);b&&g.on(e,b);c&&g.pn(e,c);d&&(e.i=d);return e},o4=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return Voa(a)},p4=function(){this.g=[];
this.i=[]},q4=function(a,b){g.iq[a]=!0;
var c=g.gq();c&&c.publish.apply(c,arguments);g.iq[a]=!1},r4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.jn;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Xoa(this,a.capabilities||""),Yoa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},Xoa=function(a,b){a.capabilities.clear();
(0,g.oe)(b.split(","),g.Wa(Loa,Zoa)).forEach(function(b){a.capabilities.add(b)})},Yoa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},s4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},t4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},u4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},$oa=function(a){return new s4(a)},v4=function(a){return g.Na(a)?(0,g.D)(a,$oa):[]},w4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},x4=function(a){return g.Na(a)?"["+(0,g.D)(a,w4).join(",")+"]":"null"},y4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},apa=function(a){return(0,g.D)(a,function(a){return{key:a.id,
name:a.name}})},z4=function(a,b){return g.eb(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},A4=function(a,b){return g.eb(a,function(a){return t4(a,b)})},bpa=function(){var a=(0,g.rt)();
a&&Soa(a,a.g.af(!0))},B4=function(){var a=g.vt("yt-remote-connected-devices")||[];
g.Bb(a);return a},cpa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.D)(a,function(a,b){return 0==b?a:a.substring(c.length)})},C4=function(a){g.ut("yt-remote-connected-devices",a,86400)},E4=function(){if(D4)return D4;
var a=g.vt("yt-remote-device-id");a||(a=y4(),g.ut("yt-remote-device-id",a,31536E3));for(var b=B4(),c=1,d=a;g.jb(b,d);)c++,d=a+"#"+c;return D4=d},F4=function(){var a=B4(),b=E4();
g.jb(a,b);g.xt()&&g.Fb(a,b);a=cpa(a);if(0==a.length)try{g.Rs("remote_sid")}catch(c){}else try{g.Qs("remote_sid",a.join(","),-1)}catch(c){}},G4=function(){return g.vt("yt-remote-session-browser-channel")},H4=function(){return g.vt("yt-remote-local-screens")||[]},I4=function(){g.ut("yt-remote-lounge-token-expiration",!0,86400)},dpa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.D)(H4(),function(a){return a.loungeToken}),c=(0,g.D)(a,function(a){return a.loungeToken});
(0,g.sj)(c,function(a){return!g.jb(b,a)})&&I4();
g.ut("yt-remote-local-screens",a,31536E3)},epa=function(a,b){g.ut("yt-remote-session-browser-channel",a);
g.ut("yt-remote-session-screen-id",b);var c=B4(),d=E4();g.jb(c,d)||c.push(d);C4(c);F4()},J4=function(a){a||(g.wt("yt-remote-session-screen-id"),g.wt("yt-remote-session-video-id"));
F4();a=B4();g.nb(a,E4());C4(a)},L4=function(){if(!K4){var a=g.op();
a&&(K4=new g.Zo(a))}return K4?!!K4.get("yt-remote-use-staging-server"):!1},M4=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},N4=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},P4=function(a){a.length?O4(a.shift(),function(){P4(a)}):Q4()},fpa=function(a){return"chrome-extension://"+a+R4},O4=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},Q4=function(){var a=N4();
a&&a(!1,"No cast extension found")},S4=function(){if(gpa){var a=2,b=N4(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;O4("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",Q4,c)}},hpa=function(){S4();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);P4(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+R4,"//www.gstatic.com/eureka/clank"+R4])},T4=function(a,b,c){g.E.call(this);
this.A=null!=c?(0,g.y)(a,c):a;this.Tc=b;this.u=(0,g.y)(this.AC,this);this.g=!1;this.i=0;this.l=this.ya=null;this.o=[]},U4=function(){},V4=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.A=d||1;this.o=45E3;this.ba=new g.Bn(this);this.i=new g.Rg;this.i.setInterval(250)},X4=function(a,b,c){a.Hh=1;
a.Vf=a4(b.clone());a.Zg=c;a.u=!0;W4(a,null)},Y4=function(a,b,c,d,e){a.Hh=1;
a.Vf=a4(b.clone());a.Zg=null;a.u=c;e&&(a.Ez=!1);W4(a,d)},W4=function(a,b){a.mi=(0,g.B)();
Z4(a);a.mg=a.Vf.clone();b4(a.mg,"t",a.A);a.Hk=0;a.lc=a.g.ep(a.g.zk()?b:null);0<a.Kp&&(a.fn=new g.Sl((0,g.y)(a.LA,a,a.lc),a.Kp));a.ba.ca(a.lc,"readystatechange",a.kL);var c=a.Fg?g.sc(a.Fg):{};a.Zg?(a.Tn="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.lc.send(a.mg,a.Tn,a.Zg,c)):(a.Tn="GET",a.Ez&&!g.ee&&(c.Connection="close"),a.lc.send(a.mg,a.Tn,null,c));a.g.le(1)},f5=function(a,b,c){for(var d=!0;!a.xg&&a.Hk<c.length;){var e=ipa(a,c);
if(e==$4){4==b&&(a.Wf=4,a5(15),d=!1);break}else if(e==b5){a.Wf=4;a5(16);d=!1;break}else c5(a,e)}4==b&&0==c.length&&(a.Wf=1,a5(17),d=!1);a.qe=a.qe&&d;d||(d5(a),e5(a))},ipa=function(a,b){var c=a.Hk,d=b.indexOf("\n",c);
if(-1==d)return $4;c=Number(b.substring(c,d));if(isNaN(c))return b5;d+=1;if(d+c>b.length)return $4;var e=b.substr(d,c);a.Hk=d+c;return e},i5=function(a,b){a.mi=(0,g.B)();
Z4(a);var c=b?window.location.hostname:"";a.mg=a.Vf.clone();g.vn(a.mg,"DOMAIN",c);g.vn(a.mg,"t",a.A);try{a.se=new ActiveXObject("htmlfile")}catch(n){d5(a);a.Wf=7;a5(22);e5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in g5)k=g5[l];else if(l in h5)k=g5[l]=h5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
g5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Ed(g.cd("b/12014412"),d+"</body></html>");a.se.open();a.se.write(g.xd(c));a.se.close();a.se.parentWindow.m=(0,g.y)(a.CK,a);a.se.parentWindow.d=(0,g.y)(a.Py,a,!0);a.se.parentWindow.rpcClose=(0,g.y)(a.Py,a,!1);c=a.se.createElement("DIV");a.se.parentWindow.document.body.appendChild(c);d=g.nd(a.mg.toString());d=g.Ec(g.kd(d));d=g.Ed(g.cd("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Ad(c,g.xd(d));a.g.le(1)},Z4=function(a){a.Vs=(0,g.B)()+
a.o;
j5(a,a.o)},j5=function(a,b){if(null!=a.Fi)throw Error("WatchDog timer not null");
a.Fi=k5((0,g.y)(a.MK,a),b)},l5=function(a){a.Fi&&(g.v.clearTimeout(a.Fi),a.Fi=null)},e5=function(a){a.g.Pv()||a.xg||a.g.Pm(a)},d5=function(a){l5(a);
g.Ef(a.fn);a.fn=null;a.i.stop();g.Dn(a.ba);if(a.lc){var b=a.lc;a.lc=null;b.abort();b.dispose()}a.se&&(a.se=null)},c5=function(a,b){try{a.g.Jy(a,b),a.g.le(4)}catch(c){}},n5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;m5(a,b,function(e){e?c(!0):g.v.setTimeout(function(){n5(a,b,c,d,f)},f)})}},m5=function(a,b,c){var d=new Image;
d.onload=function(){try{o5(d),c(!0)}catch(e){}};
d.onerror=function(){try{o5(d),c(!1)}catch(e){}};
d.onabort=function(){try{o5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{o5(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},o5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},p5=function(a){this.g=a;
this.i=new U4},r5=function(a){var b=q5(a.g,a.Xi,"/mail/images/cleardot.gif");
a4(b);n5(b.toString(),5E3,(0,g.y)(a.QB,a),3,2E3);a.le(1)},t5=function(a){var b=a.g.F;
if(null!=b)a5(5),b?(a5(11),s5(a.g,a,!1)):(a5(12),s5(a.g,a,!0));else if(a.Ad=new V4(a,void 0,void 0,void 0),a.Ad.Fg=a.Ip,b=a.g,b=q5(b,b.zk()?a.Cj:null,a.Jp),a5(5),!g.ce||g.Wc(10))b4(b,"TYPE","xmlhttp"),Y4(a.Ad,b,!1,a.Cj,!1);else{b4(b,"TYPE","html");var c=a.Ad;a=!!a.Cj;c.Hh=3;c.Vf=a4(b.clone());i5(c,a)}},u5=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new U4;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},jpa=function(a,b){this.g=a;
this.map=b;this.context=null},v5=function(a){g.Gf.call(this,"statevent",a)},w5=function(a,b){g.Gf.call(this,"timingevent",a);
this.size=b},x5=function(a){g.Gf.call(this,"serverreachability",a)},B5=function(a){y5(a);
if(3==a.g){var b=a.ik++,c=a.Al.clone();g.vn(c,"SID",a.l);g.vn(c,"RID",b);g.vn(c,"TYPE","terminate");z5(a,c);b=new V4(a,a.l,b,void 0);b.Hh=2;b.Vf=a4(c.clone());(new Image).src=b.Vf;b.mi=(0,g.B)();Z4(b)}A5(a)},D5=function(a){a.gC(1,0);
a.Al=q5(a,null,a.Hp);C5(a)},y5=function(a){a.Lf&&(a.Lf.abort(),a.Lf=null);
a.Ob&&(a.Ob.cancel(),a.Ob=null);a.cf&&(g.v.clearTimeout(a.cf),a.cf=null);E5(a);a.wd&&(a.wd.cancel(),a.wd=null);a.Sf&&(g.v.clearTimeout(a.Sf),a.Sf=null)},F5=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new jpa(a.IG++,b));2!=a.g&&3!=a.g||C5(a)},C5=function(a){a.wd||a.Sf||(a.Sf=k5((0,g.y)(a.Oy,a),0),a.Ch=0)},I5=function(a,b){if(1==a.g){if(!b){a.ik=Math.floor(1E5*Math.random());
var c=a.ik++,d=new V4(a,"",c,void 0);d.Fg=null;var e=G5(a),f=a.Al.clone();g.vn(f,"RID",c);g.vn(f,"CVER","1");z5(a,f);X4(d,f,e);a.wd=d;a.g=2}}else 3==a.g&&(b?H5(a,b):0==a.i.length||a.wd||H5(a))},H5=function(a,b){if(b)if(6<a.yg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.ik-1;var d=G5(a)}else c=b.B,d=b.Zg;else c=a.ik++,d=G5(a);var e=a.Al.clone();g.vn(e,"SID",a.l);g.vn(e,"RID",c);g.vn(e,"AID",a.Th);z5(a,e);c=new V4(a,a.l,c,a.Ch+1);c.Fg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.wd=c;X4(c,e,d)},z5=function(a,b){if(a.Rc){var c=a.Rc.vv();
c&&g.ac(c,function(a,c){g.vn(b,c,a)})}},G5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.yg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.yg?e:f-d;try{g.ac(k,function(a,b){c.push("req"+f+"_"+b+"="+encodeURIComponent(a))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},J5=function(a){a.Ob||a.cf||(a.B=1,a.cf=k5((0,g.y)(a.Ny,a),0),a.wh=0)},L5=function(a){if(a.Ob||a.cf||3<=a.wh)return!1;
a.B++;a.cf=k5((0,g.y)(a.Ny,a),K5(a,a.wh));a.wh++;return!0},s5=function(a,b,c){a.Qn=c;
a.Ce=b.qf;a.A||D5(a)},E5=function(a){null!=a.Bg&&(g.v.clearTimeout(a.Bg),a.Bg=null)},K5=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},N5=function(a,b){if(2==b||9==b){var c=null;
a.Rc&&(c=null);var d=(0,g.y)(a.ML,a);c||(c=new g.mn("//www.google.com/images/cleardot.gif"),a4(c));m5(c.toString(),1E4,d)}else a5(2);M5(a,b)},M5=function(a,b){a.g=0;
a.Rc&&a.Rc.ru(b);A5(a);y5(a)},A5=function(a){a.g=0;
a.Ce=-1;if(a.Rc)if(0==a.o.length&&0==a.i.length)a.Rc.So();else{g.rb(a.o);var b=g.rb(a.i);a.o.length=0;a.i.length=0;a.Rc.So(b)}},q5=function(a,b,c){var d=g.wn(c);
if(""!=d.g)b&&g.on(d,b+"."+d.g),g.pn(d,d.u);else{var e=window.location;d=Woa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.jj&&g.ac(a.jj,function(a,b){g.vn(d,b,a)});
g.vn(d,"VER",a.yg);z5(a,d);return d},k5=function(a,b){if(!g.Pa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},a5=function(a){O5.dispatchEvent(new v5(O5,a))},P5=function(){},kpa=function(a,b){this.action=a;
this.params=b||{}},Q5=function(a,b){g.E.call(this);
this.g=new g.L(this.uK,0,this);g.G(this,this.g);this.Tc=5E3;this.i=0;if(g.Pa(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Pa(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},R5=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Yo;this.i=new Q5(this.gM,this);this.g=null;this.Za=!1;this.u=null;this.F="";this.D=this.o=0;this.B=[];this.I=c||!1},lpa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Qn,sessionId:a.g.l,arrayId:a.g.Th}},S5=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&I5(a.g),B5(a.g));a.D=0},T5=function(a){return!!a.g&&3==a.g.g},mpa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},U5=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=g.eh(a)||"";b&&(this.port=":"+b);this.domain=g.dh(a)||"";a=g.Zb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Yb(a,"10.0")&&(this.i=!1))},V5=function(a,b){var c=a.g;
if(g.Ga(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.nh(c+b,{})},W5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Wa(a.o,d,!0),onError:g.Wa(a.l,e),ld:g.Wa(a.u,e)};c&&(a.tb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Sq(b,a)},npa=function(){var a=X5;
Y5();Z5.push(a);$5(Z5)},a6=function(a,b){Y5();
var c=Z5,d=opa(a,String(b));0==c.length?ppa(d):($5(c),(0,g.A)(c,function(a){a(d)}))},Y5=function(){Z5||(Z5=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ja("yt.mdx.remote.debug.handlers_",Z5,void 0))},ppa=function(a){var b=(b6+1)%50;
b6=b;c6[b]=a;d6||(d6=49==b)},$5=function(a){var b=c6;
if(b[0]){var c=b6,d=d6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.A)(a,function(a){a(e)})}while(d!=c);
c6=Array(50);b6=-1;d6=!1}},opa=function(a,b){var c=((0,g.B)()-qpa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},e6=function(a){g.N.call(this);
this.B=a;this.g=[]},f6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},rpa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.oe)(a.g,function(a){return!!z4(b,a)});
for(var d=0,e=b.length;d<e;d++)c=f6(a,b[d])||c;return c},spa=function(a,b){var c=a.g.length;
a.g=(0,g.oe)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},g6=function(a,b,c,d){g.N.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.ya=NaN},i6=function(a){e6.call(this,"LocalScreenService");
this.l=a;this.i=NaN;h6(this);this.info("Initializing with "+x4(this.g))},j6=function(a){if(a.g.length){var b=(0,g.D)(a.g,function(a){return a.id}),c=V5(a.l,"/pairing/get_lounge_token_batch");
W5(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.JC,a),(0,g.y)(a.IC,a))}},h6=function(a){var b=v4(H4());
b=(0,g.oe)(b,function(a){return!a.uuid});
return rpa(a,b)},k6=function(a,b){dpa((0,g.D)(a.g,u4));
b&&I4()},m6=function(a,b){g.N.call(this);
this.A=b;var c=g.vt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.jb(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;l6("Initialized with "+g.Wg(this.g))},n6=function(a,b,c){var d=V5(a.u,"/pairing/get_screen_availability");
W5(a.u,d,{lounge_token:b.token},(0,g.y)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},o6=function(a,b){a:if(n4(b)!=n4(a.g))var c=!1;
else{c=g.hc(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(l6("Updated online screens: "+g.Wg(a.g)),a.g=b,a.M("screenChange"));tpa(a)},p6=function(a){isNaN(a.l)||g.fq(a.l);
a.l=g.dq((0,g.y)(a.Vr,a),0<a.o&&a.o<(0,g.B)()?2E4:1E4)},l6=function(a){a6("OnlineScreenService",a)},q6=function(a){var b={};
(0,g.A)(a.A(),function(a){a.token?b[a.token]=a.id:this.Ib("Requesting availability of screen w/o lounge token.")});
return b},tpa=function(a){a=g.hc(g.bc(a.g,function(a){return a}));
g.Bb(a);a.length?g.ut("yt-remote-online-screen-ids",a.join(","),60):g.wt("yt-remote-online-screen-ids")},r6=function(a){e6.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};upa(this)},t6=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Fd();if(k=(c?A4(k,c):null)||A4(k,b)){k.uuid=b;var l=s6(a,k);n6(a.i,l,function(a){e(a?l:null)})}else c?vpa(a,c,(0,g.y)(function(a){var f=s6(this,new s4({name:d,
screenId:c,loungeToken:a,dialId:b||""}));n6(this.i,f,function(a){e(a?f:null)})},a),f):e(null)},u6=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},vpa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={tb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Sq(V5(a.A,"/pairing/get_lounge_token_batch"),e)},v6=function(a){a.g=a.l.Fd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+x4(a.g))},upa=function(a){w6(a);
a.l=new i6(a.A);a.l.subscribe("screenChange",(0,g.y)(a.SC,a));v6(a);a.o=v4(g.vt("yt-remote-automatic-screen-cache")||[]);w6(a);a.info("Initializing automatic screens: "+x4(a.o));a.i=new m6(a.A,(0,g.y)(a.Fd,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.M("onlineScreenChange")},a))},s6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=A4(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.ut("yt-remote-automatic-screen-cache",(0,g.D)(a.o,u4)));w6(a);a.u[b.uuid]=b.id;g.ut("yt-remote-device-id-map",a.u,31536E3);return b},w6=function(a){a.u=g.vt("yt-remote-device-id-map")||{}},x6=function(a,b,c){g.N.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},y6=function(a,b){a6(a.P,b)},A6=function(a,b){x6.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.y)(this.mM,this);this.u=(0,g.y)(this.XK,this);this.o=g.dq((0,g.y)(function(){z6(this,null)},this),12E4)},wpa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Wg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ka,(0,g.y)(function(){y6(this,"Failed to send message: getMdxSessionStatus.")},a)):y6(a,"Sending yt message without session: "+g.Wg(b))},z6=function(a,b){g.fq(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.Qm,a),d=(0,g.y)(a.Id,a);a.Hv(b,c,d,5)}}else a.Id(Error("Waiting for session status timed out."))},B6=function(a,b,c){x6.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.N=c;this.u=null;this.B=g.Ka;this.A=NaN;this.I=(0,g.y)(this.pM,this);this.g=g.Ka},C6=function(a){a.g=a.F.QA(a.H,a.i.label,a.i.friendlyName,(0,g.y)(function(a){this.g=g.Ka;
this.Qm(a)},a),(0,g.y)(function(a){this.g=g.Ka;
this.Id(a)},a))},D6=function(a){var b={};
b.pairingCode=a.H;b.theme=a.N;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}L4()&&(b.env_useStageMdx=1);return g.lh(b)},E6=function(a,b){x6.call(this,a,b,"ManualSession");
this.g=g.dq((0,g.y)(this.Vh,this,null),150)},F6=function(a,b,c,d){g.N.call(this);
this.i=a;this.B=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.y)(this.DJ,this)},G6=function(a,b){return b?g.eb(a.l,function(a){return t4(b,a.label)},a):null},H6=function(a){a6("Controller",a)},X5=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},I6=function(a){return a.u||!!a.l.length||!!a.g},J6=function(a,b,c){b!=a.g&&(g.Ef(a.g),(a.g=b)?(c?a.M("yt-remote-cast2-receiver-resumed",b.i):a.M("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.My,a,b)),b.l?a.M("yt-remote-cast2-session-change",b.l):c&&a.g.Vh(null)):a.M("yt-remote-cast2-session-change",null))},K6=function(a){var b=a.i.PA(),c=a.g&&a.g.i;
a=(0,g.D)(b,function(a){c&&t4(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=G6(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new chrome.cast.Receiver(b,a.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Apa=function(a,b,c,d,e,f,k){xpa()?ypa(b,e,f,k)&&(M6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?N6(a,c):(window.__onGCastApiAvailable=function(b,d){b?N6(a,c):(O6("Failed to load cast API: "+d),P6(!1),M6(!1),g.wt("yt-remote-cast-available"),g.wt("yt-remote-cast-receiver"),Q6(),c(!1))},d?g.qq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?hpa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?Q4():(S4(),P4(zpa.map(fpa))))):L6("Cannot initialize because not running Chrome")},Q6=function(){L6("dispose");
var a=R6();a&&a.dispose();g.Ja("yt.mdx.remote.cloudview.instance_",null,void 0);S6(!1);g.lq(T6);T6.length=0},U6=function(){return!!g.vt("yt-remote-cast-installed")},V6=function(){var a=g.vt("yt-remote-cast-receiver");
return a?a.friendlyName:null},W6=function(){L6("clearCurrentReceiver");
g.wt("yt-remote-cast-receiver")},X6=function(){return U6()?R6()?R6().getCastSession():(O6("getCastSelector: Cast is not initialized."),null):(O6("getCastSelector: Cast API is not installed!"),null)},Z6=function(){U6()?R6()?Y6()?(L6("Requesting cast selector."),R6().requestSession()):(L6("Wait for cast API to be ready to request the session."),T6.push(g.kq("yt-remote-cast2-api-ready",Z6))):O6("requestCastSelector: Cast is not initialized."):O6("requestCastSelector: Cast API is not installed!")},$6=
function(a,b){Y6()?R6().setConnectedScreenStatus(a,b):O6("setConnectedScreenStatus called before ready.")},xpa=function(){var a=0<=g.Zb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Yw||a},Bpa=function(a,b){R6().init(a,b)},ypa=function(a,b,c,d){var e=!1;
R6()||(a=new F6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.ut("yt-remote-cast-available",a);q4("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){L6("onReceiverSelected: "+a.friendlyName);
g.ut("yt-remote-cast-receiver",a);q4("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){L6("onReceiverResumed: "+a.friendlyName);
g.ut("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){L6("onSessionChange: "+w4(a));
a||g.wt("yt-remote-cast-receiver");q4("yt-remote-cast2-session-change",a)}),g.Ja("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
L6("cloudview.createSingleton_: "+e);return e},R6=function(){return g.w("yt.mdx.remote.cloudview.instance_")},N6=function(a,b){P6(!0);
M6(!1);Bpa(a,function(a){a?(S6(!0),g.nq("yt-remote-cast2-api-ready")):(O6("Failed to initialize cast API."),P6(!1),g.wt("yt-remote-cast-available"),g.wt("yt-remote-cast-receiver"),Q6());b(a)})},L6=function(a){a6("cloudview",a)},O6=function(a){a6("cloudview",a)},P6=function(a){L6("setCastInstalled_ "+a);
g.ut("yt-remote-cast-installed",a)},Y6=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},S6=function(a){L6("setApiReady_ "+a);
g.Ja("yt.mdx.remote.cloudview.apiReady_",a,void 0)},M6=function(a){g.Ja("yt.mdx.remote.cloudview.initializing_",a,void 0)},a7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.B=0;this.g=null;this.hasNext=this.Ee=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},b7=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ee=!1;a.hasNext=!1;a.B=0;a.A=(0,g.B)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},c7=function(a){return 1==a.playerState?((0,g.B)()-a.A)/1E3:0},d7=function(a,b){a.B=b;
a.A=(0,g.B)()},e7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.B)()-a.A)/1E3+a.B;
case -1E3:return 0}return a.B},f7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&b7(a)},g7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.tc(a.g);b.hasPrevious=a.Ee;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},j7=function(a,b){g.N.call(this);
this.g=0;this.o=a;this.A=[];this.u=new p4;this.l=this.i=null;this.F=(0,g.y)(this.sH,this);this.B=(0,g.y)(this.jk,this);this.D=(0,g.y)(this.rH,this);this.H=(0,g.y)(this.FH,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ys,this),h7(this))):c=3;0!=c&&(b?this.Ys(c):g.dq((0,g.y)(function(){this.Ys(c)},this),0));
var d=X6();d&&i7(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},k7=function(a){return new a7(a.o.getPlayerContextData())},h7=function(a){(0,g.A)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.A.push(this.o.subscribe(a,g.Wa(this.AJ,a),this))},a)},l7=function(a){(0,g.A)(a.A,function(a){this.o.unsubscribeByKey(a)},a);
a.A.length=0},m7=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},o7=function(a,b,c){var d=k7(a);
d7(d,c);-1E3!=d.playerState&&(d.playerState=b);n7(a,d)},p7=function(a,b,c){a.o.sendMessage(b,c)},n7=function(a,b){l7(a);
a.o.setPlayerContextData(g7(b));h7(a)},i7=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.B),a.jk(null));
a.l=b;a.l&&(a6("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.B),a.l.media.length&&a.jk(a.l.media[0]))},q7=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=k7(a);b.contentId!=d.videoId&&a6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;d7(d,a.i.getEstimatedTime());n7(a,d)}else a6("CP","No cast media video. Ignoring state update.")},r7=function(a,b,c){return(0,g.y)(function(a){this.Ib("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Ib("Retrying "+b+" using MDx browser channel."),p7(this,b,c))},a)},s7=function(a,b,c){g.N.call(this);
this.u=NaN;this.N=!1;this.H=this.F=this.I=this.P=NaN;this.O=[];this.o=this.B=this.l=this.Pa=this.g=null;this.la=a;this.O.push(g.Sr(window,"beforeunload",(0,g.y)(this.CC,this)));this.i=[];this.Pa=new a7;this.T=b.id;this.g=Cpa(this,c);this.g.subscribe("handlerOpened",this.wH,this);this.g.subscribe("handlerClosed",this.tH,this);this.g.subscribe("handlerError",this.uH,this);this.g.subscribe("handlerMessage",this.vH,this);mpa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=this.Pa.videoId;
g.xt()&&g.ut("yt-remote-session-video-id",a)},this)},t7=function(a){a6("conn",a)},Cpa=function(a,b){return new R5(V5(a.la,"/bc"),b)},u7=function(a,b){a.M("proxyStateChange",b)},Dpa=function(a){a.u=g.dq((0,g.y)(function(){t7("Connecting timeout");
this.A(1)},a),2E4)},v7=function(a){g.fq(a.u);
a.u=NaN},w7=function(a){g.fq(a.P);
a.P=NaN},Epa=function(a){x7(a);
a.I=g.dq((0,g.y)(function(){y7(this,"getNowPlaying")},a),2E4)},x7=function(a){g.fq(a.I);
a.I=NaN},A7=function(a,b){b&&(v7(a),w7(a));
b==(T5(a.g)&&isNaN(a.u))?b&&(u7(a,1),y7(a,"getSubtitlesTrack")):b?(a.V()&&a.Pa.reset(),u7(a,1),y7(a,"getNowPlaying"),z7(a)):a.A(1)},Fpa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Pa.videoId&&(g.nc(b.params)?a.Pa.g=null:a.Pa.g=b.params,a.M("remotePlayerChange"))},B7=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Pa.listId=b.params.listId||a.Pa.listId;f7(a.Pa,c,d);a.M("remoteQueueChange")},Gpa=function(a,b){b.params=b.params||{};
B7(a,b);C7(a,b);a.M("autoplayDismissed")},C7=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
d7(a.Pa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Pa.playerState&&(c=-1E3);a.Pa.playerState=c;c=Number(b.params.loadedTime);a.Pa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Pa.D=isNaN(c)?0:c;c=a.Pa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Pa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Pa.playerState?Epa(a):x7(a);a.M("remotePlayerChange")},Hpa=function(a,b){if(-1E3!=
a.Pa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Pa.playerState=c;c=parseInt(b.params.currentTime,10);d7(a.Pa,isNaN(c)?0:c);a.M("remotePlayerChange")}},Ipa=function(a,b){var c="true"==b.params.muted;
a.Pa.volume=parseInt(b.params.volume,10);a.Pa.muted=c;a.M("remotePlayerChange")},Jpa=function(a,b){a.B=b.params.videoId;
a.M("nowAutoplaying",parseInt(b.params.timeout,10))},Kpa=function(a,b){var c="true"==b.params.hasNext;
a.Pa.Ee="true"==b.params.hasPrevious;a.Pa.hasNext=c;a.M("previousNextChange")},z7=function(a){g.fq(a.H);
a.H=g.dq((0,g.y)(a.A,a,1),864E5)},y7=function(a,b,c){c?t7("Sending: action="+b+", params="+g.Wg(c)):t7("Sending: action="+b);
a.g.sendMessage(b,c)},D7=function(a){e6.call(this,"ScreenServiceProxy");
this.Dc=a;this.i=[];this.i.push(this.Dc.$_s("screenChange",(0,g.y)(this.kM,this)));this.i.push(this.Dc.$_s("onlineScreenChange",(0,g.y)(this.dJ,this)))},Ppa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Xp("MDX_CONFIG")||b;bpa();F4();E7||(E7=new U5(b?b.loungeApiHost:void 0),L4()&&(E7.g="/api/loungedev"));F7||(F7=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ja("yt.mdx.remote.deferredProxies_",F7,void 0));Lpa();var c=G7();if(!c){var d=new r6(E7);g.Ja("yt.mdx.remote.screenService_",d,void 0);c=G7();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Apa(a,d,function(a){a?H7()&&$6(H7(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){q4("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ja("yt.mdx.remote.initialized_",!0,void 0),I7("Initializing: "+g.Wg(b)),J7.push(g.kq("yt-remote-cast2-availability-change",function(){q4("yt-remote-receiver-availability-change")})),J7.push(g.kq("yt-remote-cast2-receiver-selected",function(){K7(null);
q4("yt-remote-auto-connect","cast-selector-receiver")})),J7.push(g.kq("yt-remote-cast2-receiver-resumed",function(){q4("yt-remote-receiver-resumed","cast-selector-receiver")})),J7.push(g.kq("yt-remote-cast2-session-change",Mpa)),J7.push(g.kq("yt-remote-connection-change",function(a){a?$6(H7(),"YouTube TV"):L7()||($6(null,null),W6())})),a=M7(),b.isAuto&&(a.id+="#dial"),g.wq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),I7(" -- with channel params: "+
g.Wg(a)),Npa(a),c.start(),H7()||Opa())},Qpa=function(){var a=N7();
U6()&&g.vt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},N7=function(){var a=G7().Dc.$_gos();
var b=O7();b&&P7()&&(z4(a,b)||a.push(b));return apa(a)},Q7=function(){var a=Rpa();
!a&&U6()&&V6()&&(a={key:"cast-selector-receiver",name:V6()});return a},Rpa=function(){var a=N7(),b=O7();
b||(b=L7());return g.eb(a,function(a){return b&&t4(b,a.key)?!0:!1})},O7=function(){var a=H7();
if(!a)return null;var b=G7().Fd();return A4(b,a)},Mpa=function(a){I7("remote.onCastSessionChange_: "+w4(a));
if(a){var b=O7();b&&b.id==a.id?$6(b.id,"YouTube TV"):(b&&R7(),S7(a,1))}else P7()&&R7()},R7=function(){Y6()?R6().stopSession():O6("stopSession called before API ready.");
var a=P7();a&&(a.disconnect(1),T7(null))},U7=function(){var a=P7();
return!!a&&3!=a.getProxyState()},I7=function(a){a6("remote",a)},G7=function(){if(!V7){var a=g.w("yt.mdx.remote.screenService_");
V7=a?new D7(a):null}return V7},H7=function(){return g.w("yt.mdx.remote.currentScreenId_")},W7=function(a){g.Ja("yt.mdx.remote.currentScreenId_",a,void 0)},X7=function(){return g.w("yt.mdx.remote.connectData_")},K7=function(a){g.Ja("yt.mdx.remote.connectData_",a,void 0)},P7=function(){return g.w("yt.mdx.remote.connection_")},T7=function(a){var b=P7();
K7(null);a||W7("");g.Ja("yt.mdx.remote.connection_",a,void 0);F7&&((0,g.A)(F7,function(b){b(a)}),F7.length=0);
b&&!a?q4("yt-remote-connection-change",!1):!b&&a&&q4("yt-remote-connection-change",!0)},L7=function(){var a=g.xt();
if(!a)return null;var b=G7().Fd();return A4(b,a)},S7=function(a,b){O7()&&O7();
W7(a.id);var c=new s7(E7,a,M7());c.connect(b,X7());c.subscribe("beforeDisconnect",function(a){q4("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){P7()&&T7(null)});
T7(c)},Opa=function(){var a=L7();
a?(I7("Resume connection to: "+w4(a)),S7(a,0)):(J4(),W6(),I7("Skipping connecting because no session screen found."))},Lpa=function(){var a=M7();
if(g.nc(a)){a=E4();var b=g.vt("yt-remote-session-name")||"",c=g.vt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ja("yt.mdx.remote.channelParams_",a,void 0)}},M7=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Npa=function(a){a?(g.ut("yt-remote-session-app",a.app),g.ut("yt-remote-session-name",a.name)):(g.wt("yt-remote-session-app"),g.wt("yt-remote-session-name"));
g.Ja("yt.mdx.remote.channelParams_",a,void 0)},Y7=function(a,b,c){g.E.call(this);
this.u=a;this.i=b;this.l=new g.es(this);g.G(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.sI);this.l.K(b,"captionschanged",this.qH);this.l.K(b,"captionssettingschanged",this.eA);this.l.K(b,"videoplayerreset",this.Rm);this.l.K(b,"mdxautoplaycancel",this.PB);this.O=this.l.K(b,"onVolumeChange",this.wy);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Iy,this);c.subscribe("remotePlayerChange",this.lk,this);c.subscribe("remoteQueueChange",this.Rm,this);c.subscribe("autoplayUpNext",this.jy,
this);c.subscribe("previousNextChange",this.Fy,this);c.subscribe("nowAutoplaying",this.By,this);c.subscribe("autoplayDismissed",this.iy,this);this.suggestion=null;this.F=new g.PC(64);this.o=new g.L(this.cA,500,this);g.G(this,this.o);this.A=new g.L(this.dA,1E3,this);g.G(this,this.A);this.I=new T4(this.UL,0,this);g.G(this,this.I);this.B={};this.P=new g.L(this.DA,1E3,this);g.G(this,this.P);this.H=new g.Sl(this.ZE,1E3,this);g.G(this,this.H);this.N=g.Ka;this.eA();this.Rm();this.lk()},Z7=function(a,b){a.u.nd(b,
a.i.getVideoData().lengthSeconds)},a8=function(a){Z7(a,0);
a.o.stop();$7(a,new g.PC(64))},c8=function(a,b){if(b8(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.vc(c,b));a.g.Sz(a.i.getVideoData(1).videoId,c);a.B=k7(a.g).g}},d8=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Sa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Mh,m4(c));$7(a,new g.PC(1))},e8=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{DP:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},b8=function(a){return k7(a.g).videoId==a.i.getVideoData(1).videoId},$7=function(a,b){a.A.stop();
var c=a.F;if(!g.VC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.GJ(a.i,d);a.F=b;f8(a.u,c,b)}},h8=function(a){g.S.call(this,{C:"div",
G:"ytp-remote",J:[{C:"div",G:"ytp-remote-display-status",J:[{C:"div",G:"ytp-remote-display-status-icon",J:[g.KO()]},{C:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.uP(this,250);g.G(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);g8(this,g.CJ(a))},g8=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.BN("Error en $RECEIVER_NAME",c):g.WC(b)||g.U(b,4)?g.BN("Reproduciendo en $RECEIVER_NAME",c):g.BN("Conectado a $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},i8=function(a,b){g.cT.call(this,"Reproducir en",0,a,b);
this.l=a;this.D={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},j8=function(a){g.fK.call(this,a);
this.i={key:y4(),name:"Esta computadora"};this.o=null;this.u=[];this.B=this.g=null;this.A=[this.i];this.l=this.i;this.Xj=new g.PC(64);this.D=0;this.gm=-1;if(!g.Vy(g.V(this.player))){a=this.player;var b=g.nC(a);b&&(b=b.Bm())&&(b=new i8(a,b),g.G(this,b));b=new h8(a);g.G(this,b);g.TJ(a,b.element,4)}},f8=function(a,b,c){a.Xj=c;
a.player.M("presentingplayerstatechange",new g.$C(c,b))},k8=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)R7();
else{a.l=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.na(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Mh,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=m4(d))&&(c.locationInfo=d);d=c}else d=null;I7("Connecting to: "+g.Wg(b));"cast-selector-receiver"==b.key?
(K7(d||null),Y6()?R6().setLaunchParams(d||null):O6("setLaunchParams called before ready.")):!d&&U7()&&H7()==b.key?q4("yt-remote-connection-change",!0):(R7(),K7(d||null),d=G7().Fd(),(d=A4(d,b.key))&&S7(d,1))}},Qoa=/^https?$/i,Spa=["POST",
"PUT"];g.z(k4,g.eg);g.h=k4.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.u=0;this.aa=b;this.O=!1;this.i=!0;this.g=this.N?c4(this.N):c4(g.fY);this.P=this.N?this.N.getOptions():g.fY.getOptions();this.g.onreadystatechange=(0,g.y)(this.Rv,this);try{$3(d4(this,"Opening Xhr")),this.T=!0,this.g.open(b,String(a),!0),this.T=!1}catch(f){$3(d4(this,"Error opening Xhr: "+f.message));h4(this,f);return}a=c||
"";var e=this.headers.clone();d&&Noa(d,function(a,b){e.set(b,a)});
d=g.eb(e.Ed(),Ooa);c=g.v.FormData&&a instanceof g.v.FormData;!g.jb(Spa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.g.setRequestHeader(b,a)},this);
this.Y&&(this.g.responseType=this.Y);"withCredentials"in this.g&&this.g.withCredentials!==this.V&&(this.g.withCredentials=this.V);try{e4(this),0<this.A&&(this.I=Poa(this.g),$3(d4(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.y)(this.Sv,this)):this.B=g.Sg(this.Sv,this.A,this)),$3(d4(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){$3(d4(this,"Send error: "+f.message)),h4(this,f)}};
g.h.Sv=function(){"undefined"!=typeof g.KX&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,d4(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(d4(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),g4(this))};
g.h.R=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),g4(this,!0));k4.Ha.R.call(this)};
g.h.Rv=function(){this.da()||(this.T||this.D||this.o?j4(this):this.CJ())};
g.h.CJ=function(){j4(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<i4(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.t(this.l)?this.l:String(this.l)};
var h5={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},g5={"'":"\\'"},Tpa={};g.h=p4.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.jb(this.g,a)||g.jb(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.zla)(b,a);0<=c?(g.lb(b,c),b=!0):b=!1;return b||g.nb(this.i,a)};
g.h.uc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var Zoa={IM:"atp",SO:"ska",IO:"que",jO:"mus",RO:"sus",AN:"dsp",OO:"seq"};r4.prototype.Mf=function(){var a=new r4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var K4,D4="",R4=M4("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",gpa=M4("loadCastFramework")||M4("loadCastApplicationFramework"),zpa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.z(T4,g.E);g.h=T4.prototype;g.h.zC=function(a){this.o=arguments;this.g=!1;this.ya?this.l=(0,g.B)()+this.Tc:this.ya=g.Sg(this.u,this.Tc)};
g.h.stop=function(){this.ya&&(g.v.clearTimeout(this.ya),this.ya=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.R=function(){this.stop();T4.Ha.R.call(this)};
g.h.AC=function(){this.l?(this.ya=g.Sg(this.u,this.l-(0,g.B)()),this.l=null):(this.ya=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};U4.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
U4.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=V4.prototype;g.h.Fg=null;g.h.qe=!1;g.h.Fi=null;g.h.Vs=null;g.h.mi=null;g.h.Hh=null;g.h.Vf=null;g.h.mg=null;g.h.Zg=null;g.h.lc=null;g.h.Hk=0;g.h.se=null;g.h.Tn=null;g.h.Wf=null;g.h.Dj=-1;g.h.Ez=!0;g.h.xg=!1;g.h.Kp=0;g.h.fn=null;var b5={},$4={};g.h=V4.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.kL=function(a){a=a.target;var b=this.fn;b&&3==i4(a)?b.zj():this.LA(a)};
g.h.LA=function(a){try{if(a==this.lc)a:{var b=i4(this.lc),c=this.lc.u,d=this.lc.getStatus();if(g.ce&&!g.Wc(10)||g.ee&&!g.Vc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Oh&&!l4(this.lc))break a;this.xg||4!=b||7==c||(8==c||0>=d?this.g.le(3):this.g.le(2));l5(this);var e=this.lc.getStatus();this.Dj=e;var f=l4(this.lc);(this.qe=200==e)?(4==b&&d5(this),this.u?(f5(this,b,f),g.Oh&&this.qe&&3==b&&(this.ba.ca(this.i,"tick",this.gL),this.i.start())):c5(this,f),this.qe&&!this.xg&&(4==b?this.g.Pm(this):(this.qe=
!1,Z4(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Wf=3,a5(13)):(this.Wf=0,a5(14)),d5(this),e5(this))}}catch(k){this.lc&&l4(this.lc)}finally{}};
g.h.gL=function(){var a=i4(this.lc),b=l4(this.lc);this.Hk<b.length&&(l5(this),f5(this,a,b),this.qe&&4!=a&&Z4(this))};
g.h.CK=function(a){k5((0,g.y)(this.BK,this,a),0)};
g.h.BK=function(a){this.xg||(l5(this),c5(this,a),Z4(this))};
g.h.Py=function(a){k5((0,g.y)(this.AK,this,a),0)};
g.h.AK=function(a){this.xg||(d5(this),this.qe=a,this.g.Pm(this),this.g.le(4))};
g.h.cancel=function(){this.xg=!0;d5(this)};
g.h.MK=function(){this.Fi=null;var a=(0,g.B)();0<=a-this.Vs?(2!=this.Hh&&this.g.le(3),d5(this),this.Wf=2,a5(18),e5(this)):j5(this,this.Vs-a)};
g.h.getLastError=function(){return this.Wf};g.h=p5.prototype;g.h.Ip=null;g.h.Ad=null;g.h.gn=!1;g.h.Qv=null;g.h.yl=null;g.h.yq=null;g.h.Jp=null;g.h.Ud=null;g.h.qf=-1;g.h.Cj=null;g.h.Xi=null;g.h.connect=function(a){this.Jp=a;a=q5(this.g,null,this.Jp);a5(3);this.Qv=(0,g.B)();var b=this.g.D;null!=b?(this.Cj=b[0],(this.Xi=b[1])?(this.Ud=1,r5(this)):(this.Ud=2,t5(this))):(b4(a,"MODE","init"),this.Ad=new V4(this,void 0,void 0,void 0),this.Ad.Fg=this.Ip,Y4(this.Ad,a,!1,null,!0),this.Ud=0)};
g.h.QB=function(a){if(a)this.Ud=2,t5(this);else{a5(4);var b=this.g;b.Ce=b.Lf.qf;N5(b,9)}a&&this.le(2)};
g.h.ep=function(a){return this.g.ep(a)};
g.h.abort=function(){this.Ad&&(this.Ad.cancel(),this.Ad=null);this.qf=-1};
g.h.Pv=function(){return!1};
g.h.Jy=function(a,b){this.qf=a.Dj;if(0==this.Ud)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ce=this.qf;N5(c,2);return}this.Cj=c[0];this.Xi=c[1]}else c=this.g,c.Ce=this.qf,N5(c,2);else if(2==this.Ud)if(this.gn)a5(7),this.yq=(0,g.B)();else if("11111"==b){if(a5(6),this.gn=!0,this.yl=(0,g.B)(),c=this.yl-this.Qv,!g.ce||g.Wc(10)||500>c)this.qf=200,this.Ad.cancel(),a5(12),s5(this.g,this,!0)}else a5(8),this.yl=this.yq=(0,g.B)(),this.gn=!1};
g.h.Pm=function(){this.qf=this.Ad.Dj;if(this.Ad.qe)0==this.Ud?this.Xi?(this.Ud=1,r5(this)):(this.Ud=2,t5(this)):2==this.Ud&&((!g.ce||g.Wc(10)?!this.gn:200>this.yq-this.yl)?(a5(11),s5(this.g,this,!1)):(a5(12),s5(this.g,this,!0)));else{0==this.Ud?a5(9):2==this.Ud&&a5(10);var a=this.g;this.Ad.getLastError();a.Ce=this.qf;N5(a,2)}};
g.h.zk=function(){return this.g.zk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.le=function(a){this.g.le(a)};g.h=u5.prototype;g.h.jj=null;g.h.wd=null;g.h.Ob=null;g.h.Hp=null;g.h.Al=null;g.h.ju=null;g.h.Jl=null;g.h.ik=0;g.h.IG=0;g.h.Rc=null;g.h.Sf=null;g.h.cf=null;g.h.Bg=null;g.h.Lf=null;g.h.Qn=null;g.h.Th=-1;g.h.yw=-1;g.h.Ce=-1;g.h.Ch=0;g.h.wh=0;g.h.yg=8;var O5=new g.eg;g.z(v5,g.Gf);g.z(w5,g.Gf);g.z(x5,g.Gf);g.h=u5.prototype;g.h.connect=function(a,b,c,d,e){a5(0);this.Hp=b;this.jj=c||{};d&&g.Ga(e)&&(this.jj.OSID=d,this.jj.OAID=e);this.A?(k5((0,g.y)(this.Bu,this,a),100),D5(this)):this.Bu(a)};
g.h.Bu=function(a){this.Lf=new p5(this);this.Lf.Ip=null;this.Lf.i=this.u;this.Lf.connect(a)};
g.h.Pv=function(){return 0==this.g};
g.h.Oy=function(a){this.Sf=null;I5(this,a)};
g.h.Ny=function(){this.cf=null;this.Ob=new V4(this,this.l,"rpc",this.B);this.Ob.Fg=null;this.Ob.Kp=0;var a=this.ju.clone();g.vn(a,"RID","rpc");g.vn(a,"SID",this.l);g.vn(a,"CI",this.Qn?"0":"1");g.vn(a,"AID",this.Th);z5(this,a);if(!g.ce||g.Wc(10))g.vn(a,"TYPE","xmlhttp"),Y4(this.Ob,a,!0,this.Jl,!1);else{g.vn(a,"TYPE","html");var b=this.Ob,c=!!this.Jl;b.Hh=3;b.Vf=a4(a.clone());i5(b,c)}};
g.h.Jy=function(a,b){if(0!=this.g&&(this.Ob==a||this.wd==a))if(this.Ce=a.Dj,this.wd==a&&3==this.g)if(7<this.yg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Na(c)&&3==c.length)if(0==c[0])a:{if(!this.cf){if(this.Ob)if(this.Ob.mi+3E3<this.wd.mi)E5(this),this.Ob.cancel(),this.Ob=null;else break a;L5(this);a5(19)}}else this.yw=c[1],0<this.yw-this.Th&&37500>c[2]&&this.Qn&&0==this.wh&&!this.Bg&&(this.Bg=k5((0,g.y)(this.mH,this),6E3));else N5(this,11)}else b!=Tpa.gN.g&&N5(this,11);else if(this.Ob==a&&
E5(this),!g.Mb(b)){c=this.u.parse(b);g.Na(c);for(var d=0;d<c.length;d++){var e=c[d];this.Th=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Jl=e[2],e=e[3],null!=e?this.yg=e:this.yg=6,this.g=3,this.Rc&&this.Rc.uu(),this.ju=q5(this,this.zk()?this.Jl:null,this.Hp),J5(this)):"stop"==e[0]&&N5(this,7):3==this.g&&("stop"==e[0]?N5(this,7):"noop"!=e[0]&&this.Rc&&this.Rc.tu(e),this.wh=0)}}};
g.h.mH=function(){null!=this.Bg&&(this.Bg=null,this.Ob.cancel(),this.Ob=null,L5(this),a5(20))};
g.h.Pm=function(a){if(this.Ob==a){E5(this);this.Ob=null;var b=2}else if(this.wd==a)this.wd=null,b=1;else return;this.Ce=a.Dj;if(0!=this.g)if(a.qe)1==b?(b=(0,g.B)()-a.mi,O5.dispatchEvent(new w5(O5,a.Zg?a.Zg.length:0,b,this.Ch)),C5(this),this.o.length=0):J5(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ce)){if(d=1==b)this.wd||this.Sf||1==this.g||2<=this.Ch?d=!1:(this.Sf=k5((0,g.y)(this.Oy,this,a),K5(this,this.Ch)),this.Ch++,d=!0);d=!(d||2==b&&L5(this))}if(d)switch(c){case 1:N5(this,
5);break;case 4:N5(this,10);break;case 3:N5(this,6);break;case 7:N5(this,12);break;default:N5(this,2)}}};
g.h.gC=function(a){if(!g.jb(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.ML=function(a){a?a5(2):(a5(1),M5(this,8))};
g.h.ep=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new k4;a.V=!1;return a};
g.h.isActive=function(){return!!this.Rc&&this.Rc.isActive(this)};
g.h.le=function(a){O5.dispatchEvent(new x5(O5,a))};
g.h.zk=function(){return!(!g.ce||g.Wc(10))};
g.h=P5.prototype;g.h.uu=function(){};
g.h.tu=function(){};
g.h.ru=function(){};
g.h.So=function(){};
g.h.vv=function(){return{}};
g.h.isActive=function(){return!0};g.z(Q5,g.E);g.h=Q5.prototype;g.h.uK=function(){this.Tc=Math.min(3E5,2*this.Tc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Tc+15E3*Math.random();g.Do(this.g,a);this.i=(0,g.B)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Tc=5E3};g.z(R5,P5);g.h=R5.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.wf=function(a){return this.l.Gg(a)};
g.h.M=function(a,b){return this.l.M.apply(this.l,arguments)};
g.h.dispose=function(){this.Za||(this.Za=!0,g.Ef(this.l),S5(this),g.Ef(this.i),this.i=null)};
g.h.da=function(){return this.Za};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new u5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Rc=null);d.Rc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.Th):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.vc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):T5(this)&&F5(this.g,c)};
g.h.uu=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)F5(this.g,a[b])}this.M("handlerOpened")};
g.h.ru=function(a){var b=2==a&&401==this.g.Ce;4==a||b||this.i.start();this.M("handlerError",a)};
g.h.So=function(a){if(!this.i.isActive())this.M("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.vv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.vc(a,this.u);return a};
g.h.tu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),B5(this.g)):this.M("handlerMessage",new kpa(a[0],a[1]))};
g.h.gM=function(){this.i.isActive();var a=this.g,b=0;a.Ob&&b++;a.wd&&b++;0!=b||this.connect(this.u,this.o)};U5.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
U5.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
U5.prototype.u=function(a){a(Error("request timed out"))};var qpa=(0,g.B)(),Z5=null,c6=Array(50),b6=-1,d6=!1;g.z(e6,g.N);e6.prototype.Fd=function(){return this.g};
e6.prototype.contains=function(a){return!!z4(this.g,a)};
e6.prototype.get=function(a){return a?A4(this.g,a):null};
e6.prototype.info=function(a){a6(this.B,a)};g.z(g6,g.N);var l8=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=g6.prototype;g.h.start=function(){!this.g&&isNaN(this.ya)&&this.OA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.ya)||(g.fq(this.ya),this.ya=NaN)};
g.h.R=function(){this.stop();g6.Ha.R.call(this)};
g.h.OA=function(){this.ya=NaN;this.g=g.Sq(V5(this.A,"/pairing/get_screen"),{method:"POST",tb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.y)(this.iM,this),onError:(0,g.y)(this.hM,this),ld:(0,g.y)(this.jM,this)})};
g.h.iM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.M("pairingComplete",new s4(c))};
g.h.hM=function(a){this.g=null;a.status&&404==a.status?this.i>=l8.length?this.M("pairingFailed",Error("DIAL polling timed out")):(a=l8[this.i],this.ya=g.dq((0,g.y)(this.OA,this),a),this.i++):this.M("pairingFailed",Error("Server error "+a.status))};
g.h.jM=function(){this.g=null;this.M("pairingFailed",Error("Server not responding"))};g.z(i6,e6);g.h=i6.prototype;g.h.start=function(){h6(this)&&this.M("screenChange");!g.vt("yt-remote-lounge-token-expiration")&&j6(this);g.fq(this.i);this.i=g.dq((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){h6(this);f6(this,a);k6(this,!1);this.M("screenChange");b(a);a.token||j6(this)};
g.h.remove=function(a,b){var c=h6(this);spa(this,a)&&(k6(this,!1),c=!0);b(a);c&&this.M("screenChange")};
g.h.Mn=function(a,b,c,d){var e=h6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.M("screenChange")};
g.h.R=function(){g.fq(this.i);i6.Ha.R.call(this)};
g.h.JC=function(a){h6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k6(this,!b);b&&a6(this.B,"Missed "+b+" lounge tokens.")};
g.h.IC=function(a){a6(this.B,"Requesting lounge tokens failed: "+a)};g.z(m6,g.N);g.h=m6.prototype;g.h.start=function(){var a=parseInt(g.vt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.B)()-144E5<a?0:a)?p6(this):(this.o=(0,g.B)()+3E5,g.ut("yt-remote-fast-check-period",this.o),this.Vr())};
g.h.isEmpty=function(){return g.nc(this.g)};
g.h.update=function(){l6("Updating availability on schedule.");var a=this.A(),b=g.bc(this.g,function(b,d){return b&&!!A4(a,d)},this);
o6(this,b)};
g.h.R=function(){g.fq(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);m6.Ha.R.call(this)};
g.h.Vr=function(){g.fq(this.l);this.l=NaN;this.i&&this.i.abort();var a=q6(this);if(n4(a)){var b=V5(this.u,"/pairing/get_screen_availability");this.i=W5(this.u,b,{lounge_token:g.hc(a).join(",")},(0,g.y)(this.YJ,this,a),(0,g.y)(this.XJ,this))}else o6(this,{}),p6(this)};
g.h.YJ=function(a,b){this.i=null;var c=g.hc(q6(this));if(g.Eb(c,g.hc(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;o6(this,d);p6(this)}else this.Ib("Changing Screen set during request."),this.Vr()};
g.h.XJ=function(a){this.Ib("Screen availability failed: "+a);this.i=null;p6(this)};
g.h.Ib=function(a){a6("OnlineScreenService",a)};g.z(r6,e6);g.h=r6.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.M("screenChange"),this.i.isEmpty()||this.M("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Mn=function(a,b,c,d){this.l.contains(a)?this.l.Mn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,a6(this.B,a),d(Error(a)))};
g.h.Fd=function(a){return a?this.g:g.qb(this.g,(0,g.oe)(this.o,function(a){return!this.contains(a)},this))};
g.h.PA=function(){return(0,g.oe)(this.Fd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.QA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new g6(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(a){g.Ef(f);d(s6(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Ef(f);e(a)});
f.start();return(0,g.y)(f.stop,f)};
g.h.lM=function(a,b,c,d){g.Sq(V5(this.A,"/pairing/get_screen"),{method:"POST",tb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(a,d){var e=new s4(d.screen||{});if(!e.name||u6(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);u6(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(s6(this,e))},this),
onError:(0,g.y)(function(a){d(Error("pairing request failed: "+a.status))},this),
ld:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.R=function(){g.Ef(this.l);g.Ef(this.i);r6.Ha.R.call(this)};
g.h.SC=function(){v6(this);this.M("screenChange");this.i.update()};
r6.prototype.dispose=r6.prototype.dispose;g.z(x6,g.N);g.h=x6.prototype;g.h.Qm=function(a){this.l=a;this.M("sessionScreen",this.l)};
g.h.Id=function(a){this.da()||(a&&y6(this,""+a),this.l=null,this.M("sessionScreen",null))};
g.h.info=function(a){a6(this.P,a)};
g.h.SA=function(){return null};
g.h.ms=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){y6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.R=function(){this.ms("");x6.Ha.R.call(this)};g.z(A6,x6);g.h=A6.prototype;g.h.ls=function(a){if(this.g){if(this.g==a)return;y6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);wpa(this)};
g.h.Vh=function(a){this.info("launchWithParams no-op for Cast: "+g.Wg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Id()},this),(0,g.y)(function(){this.Id(Error("Failed to stop receiver app."))},this)):this.Id(Error("Stopping cast device witout session."))};
g.h.ms=g.Ka;g.h.R=function(){this.info("disposeInternal");g.fq(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;A6.Ha.R.call(this)};
g.h.XK=function(a,b){if(!this.da())if(b){var c=o4(b);if(g.Qa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Wg(c));switch(d){case "mdxSessionStatus":z6(this,c.screenId);break;default:y6(this,"Unknown youtube message: "+d)}}else y6(this,"Unable to parse message.")}else y6(this,"No data in message.")};
g.h.Hv=function(a,b,c,d){t6(this.F,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(y6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.dq((0,g.y)(this.Hv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.SA=function(){return this.g};
g.h.mM=function(a){this.da()||a||(y6(this,"Cast session died."),this.Id())};g.z(B6,x6);g.h=B6.prototype;g.h.ls=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.Vh=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ka;g.fq(this.A);this.o?this.o.stop((0,g.y)(this.Id,this,null),(0,g.y)(this.Id,this,"Failed to stop DIAL device.")):this.Id()};
g.h.R=function(){this.g();this.g=g.Ka;g.fq(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;B6.Ha.R.call(this)};
g.h.pM=function(a){this.da()||a||(y6(this,"DIAL session died."),this.g(),this.g=g.Ka,this.Id())};
g.h.Yp=function(a){this.H=y4();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,D6(this));a(b);C6(this)}else this.B=(0,g.y)(function(){g.fq(this.A);this.B=g.Ka;this.A=NaN;var b=new chrome.cast.DialLaunchResponse(!0,D6(this));a(b);C6(this)},this),this.A=g.dq((0,g.y)(function(){this.B()},this),100)};
g.h.nD=function(a,b,c){t6(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.y)(function(a){a&&a.token?(this.Qm(a),b(new chrome.cast.DialLaunchResponse(!1))):this.Yp(b,c)},this),(0,g.y)(function(a){y6(this,"Failed to get DIAL screen: "+a);
this.Yp(b,c)},this))};g.z(E6,x6);E6.prototype.stop=function(){this.Id()};
E6.prototype.ls=g.Ka;E6.prototype.Vh=function(){g.fq(this.g);this.g=NaN;var a=A4(this.F.Fd(),this.i.label);a?this.Qm(a):this.Id(Error("No such screen"))};
E6.prototype.R=function(){g.fq(this.g);this.g=NaN;E6.Ha.R.call(this)};g.z(F6,g.N);g.h=F6.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.y)(this.Ly,this),(0,g.y)(this.HJ,this),d,e);c.customDialLaunchCallback=(0,g.y)(this.OH,this);chrome.cast.initialize(c,(0,g.y)(function(){this.da()||
(chrome.cast.addReceiverActionListener(this.o),npa(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.RA,this)),this.l=K6(this),chrome.cast.setCustomReceivers(this.l,g.Ka,(0,g.y)(function(a){this.Ib("Failed to set initial custom receivers: "+g.Wg(a))},this)),this.M("yt-remote-cast2-availability-change",I6(this)),b(!0))},this),(0,g.y)(function(a){this.Ib("Failed to initialize API: "+g.Wg(a));
b(!1)},this))};
g.h.CL=function(a,b){H6("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)H6("Unsetting old screen status: "+this.g.i.friendlyName),J6(this,null)}if(a&&b){if(!this.g){c=A4(this.i.Fd(),a);if(!c){H6("setConnectedScreenStatus: Unknown screen.");return}var d=G6(this,c);d||(H6("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ka,(0,g.y)(function(a){this.Ib("Failed to set initial custom receivers: "+g.Wg(a))},this)));
H6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);J6(this,new E6(this.i,d),!0)}this.g.ms(b)}else H6("setConnectedScreenStatus: no screen.")};
g.h.DL=function(a){this.da()?this.Ib("Setting connection data on disposed cast v2"):this.g?this.g.Vh(a):this.Ib("Setting connection data without a session")};
g.h.oM=function(){this.da()?this.Ib("Stopping session on disposed cast v2"):this.g?(this.g.stop(),J6(this,null)):H6("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.Ly,this),(0,g.y)(this.dK,this))};
g.h.R=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.RA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.nb(g.w("yt.mdx.remote.debug.handlers_")||[],X5);g.Ef(this.g);F6.Ha.R.call(this)};
g.h.Ib=function(a){a6("Controller",a)};
g.h.My=function(a,b){this.g==a&&(b||J6(this,null),this.M("yt-remote-cast2-session-change",b))};
g.h.DJ=function(a,b){if(!this.da())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),H6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)H6("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{H6("onReceiverAction_: Casting to active receiver.");this.g.l&&this.M("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:J6(this,
new E6(this.i,a));break;case chrome.cast.ReceiverType.DIAL:J6(this,new B6(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:J6(this,new A6(this.i,a));break;default:this.Ib("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Ib("Stopping receiver w/o session: "+a.friendlyName)}else this.Ib("onReceiverAction_ called without receiver.")};
g.h.OH=function(a){if(this.da())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Ib("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Ib("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return H6("Reselecting dial screen."),
this.M("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Ib('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);J6(this,new B6(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.nD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.y)(b.Yp,b))};
g.h.Ly=function(a){if(!this.da()){H6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)H6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),J6(this,new A6(this.i,b),!0);else{this.Ib("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=A4(this.i.Fd(),c.label);d&&t4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(H6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ef(this.g),this.g=new A6(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.My,this,this.g)),this.g.Vh(null));this.g.ls(a)}}};
g.h.nM=function(){return this.g?this.g.SA():null};
g.h.dK=function(a){this.da()||(this.Ib("Failed to estabilish a session: "+g.Wg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&J6(this,null))};
g.h.HJ=function(a){H6("Receiver availability updated: "+a);if(!this.da()){var b=I6(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;I6(this)!=b&&this.M("yt-remote-cast2-availability-change",I6(this))}};
g.h.RA=function(){this.da()||(this.l=K6(this),H6("Updating custom receivers: "+g.Wg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ka,(0,g.y)(function(){this.Ib("Failed to set custom receivers.")},this)),this.M("yt-remote-cast2-availability-change",I6(this)))};
F6.prototype.setLaunchParams=F6.prototype.DL;F6.prototype.setConnectedScreenStatus=F6.prototype.CL;F6.prototype.stopSession=F6.prototype.oM;F6.prototype.getCastSession=F6.prototype.nM;F6.prototype.requestSession=F6.prototype.requestSession;F6.prototype.init=F6.prototype.init;F6.prototype.dispose=F6.prototype.dispose;var T6=[];a7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";b7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ee=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
a7.prototype.isAdPlaying=function(){return 1081==this.playerState};
a7.prototype.getDuration=function(){return this.u?this.D+c7(this):this.D};
a7.prototype.clone=function(){return new a7(g7(this))};g.z(j7,g.N);g.h=j7.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ka,r7(this,"play")):p7(this,"play"),o7(this,1,e7(k7(this))),this.M("remotePlayerChange")):m7(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ka,r7(this,"pause")):p7(this,"pause"),o7(this,2,e7(k7(this))),this.M("remotePlayerChange")):m7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=k7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ka,r7(this,"seekTo",{newTime:a}))}else p7(this,"seekTo",{newTime:a});o7(this,3,a);this.M("remotePlayerChange")}else m7(this,g.Wa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ka,r7(this,"stopVideo")):p7(this,"stopVideo");var a=k7(this);a.index=-1;a.videoId="";b7(a);n7(this,a);this.M("remotePlayerChange")}else m7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=k7(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){a6("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Ib("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){a6("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Ib("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);p7(this,"setVolume",e)}c.muted=b;c.volume=a;n7(this,c)}else m7(this,g.Wa(this.setVolume,a,b))};
g.h.Sz=function(a,b){if(1==this.g){var c=k7(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Wg(b.style),g.vc(d,c.g));p7(this,"setSubtitlesTrack",d);n7(this,c)}else m7(this,g.Wa(this.Sz,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){p7(this,"setAudioTrack",{videoId:a,audioTrackId:b.ob.id});var c=k7(this);c.audioTrackId=b.ob.id;n7(this,c)}else m7(this,g.Wa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=k7(this);c=c||0;var m={videoId:a,currentIndex:c};f7(l,a,c);g.Ga(b)&&(d7(l,b),m.currentTime=b);g.Ga(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Wg(k));p7(this,"setPlaylist",m);d||n7(this,l)};
g.h.Zm=function(a,b){if(1==this.g){if(a&&b){var c=k7(this);f7(c,a,b);n7(this,c)}p7(this,"previous")}else m7(this,g.Wa(this.Zm,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=k7(this);f7(c,a,b);n7(this,c)}p7(this,"next")}else m7(this,g.Wa(this.nextVideo,a,b))};
g.h.Tu=function(){1==this.g?p7(this,"dismissAutoplay"):m7(this,this.Tu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.M("proxyStateChange",a,this.g)}j7.Ha.dispose.call(this)};
g.h.R=function(){l7(this);this.o=null;this.u.clear();i7(this,null);j7.Ha.R.call(this)};
g.h.Ys=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.M("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.AJ=function(a,b){this.M(a,b)};
g.h.sH=function(a){if(!a)this.jk(null),i7(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=k7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)a6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,n7(this,b)}};
g.h.jk=function(a){a6("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),q7(this),this.M("remotePlayerChange")};
g.h.rH=function(a){a?(q7(this),this.M("remotePlayerChange")):this.jk(null)};
g.h.Hs=function(){p7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.FH=function(){var a=X6();a&&i7(this,a)};
g.h.Ib=function(a){a6("CP",a)};g.z(s7,g.N);g.h=s7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ga(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ga(k)&&(l.currentIndex=k);c&&(this.Pa.listId=c);this.Pa.videoId=d;this.Pa.index=k||0;this.Pa.state=3;d7(this.Pa,m);this.o="UNSUPPORTED";t7("Connecting with setPlaylist and params: "+g.Wg(l));this.g.connect({method:"setPlaylist",
params:g.Wg(l)},a,G4())}else t7("Connecting without params"),this.g.connect({},a,G4());Dpa(this)};
g.h.dispose=function(){this.da()||(this.M("beforeDispose"),u7(this,3));s7.Ha.dispose.call(this)};
g.h.R=function(){v7(this);x7(this);w7(this);g.fq(this.F);this.F=NaN;g.fq(this.H);this.H=NaN;this.l=null;g.Tr(this.O);this.O.length=0;this.g.dispose();s7.Ha.R.call(this);this.o=this.B=this.i=this.Pa=this.g=null};
g.h.CC=function(){this.A(2)};
g.h.wH=function(){t7("Channel opened");this.N&&(this.N=!1,w7(this),this.P=g.dq((0,g.y)(function(){t7("Timing out waiting for a screen.");this.A(1)},this),15E3));
epa(lpa(this.g),this.T)};
g.h.tH=function(){t7("Channel closed");isNaN(this.u)?J4(!0):J4();this.dispose()};
g.h.uH=function(a){J4();isNaN(this.D())?(t7("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,t7("Channel error: "+a+" with reconnection in "+this.D()+" ms"),u7(this,2))};
g.h.vH=function(a){a.params?t7("Received: action="+a.action+", params="+g.Wg(a.params)):t7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=o4(a.params.devices);this.i=(0,g.D)(a,function(a){return new r4(a)});
a=!!g.eb(this.i,function(a){return"LOUNGE_SCREEN"==a.type});
A7(this,a);break;case "loungeScreenDisconnected":g.ob(this.i,function(a){return"LOUNGE_SCREEN"==a.type});
A7(this,!1);break;case "remoteConnected":var b=new r4(o4(a.params.device));g.eb(this.i,function(a){return b?a.id==b.id:!1})||Toa(this.i,b);
break;case "remoteDisconnected":b=new r4(o4(a.params.device));g.ob(this.i,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":B7(this,a);break;case "nowPlaying":Gpa(this,a);break;case "onStateChange":C7(this,a);break;case "onAdStateChange":Hpa(this,a);break;case "onVolumeChanged":Ipa(this,a);break;case "onSubtitlesTrackChanged":Fpa(this,a);break;case "nowAutoplaying":Jpa(this,a);break;case "autoplayDismissed":this.M("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.M("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.M("autoplayModeChange",this.o);"DISABLED"==this.o&&this.M("autoplayDismissed");break;case "onHasPreviousNextChanged":Kpa(this,a);break;case "requestAssistedSignIn":this.M("assistedSignInRequested",a.params.authCode);break;default:t7("Unrecognized action: "+a.action)}};
g.h.qL=function(){if(this.l){var a=this.l;this.l=null;this.Pa.videoId!=a&&y7(this,"getNowPlaying")}};
s7.prototype.subscribe=s7.prototype.subscribe;s7.prototype.unsubscribeByKey=s7.prototype.wf;s7.prototype.Z=function(){var a=3;this.da()||(a=0,isNaN(this.D())?T5(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
s7.prototype.getProxyState=s7.prototype.Z;s7.prototype.A=function(a){t7("Disconnecting with "+a);v7(this);this.M("beforeDisconnect",a);1==a&&J4();S5(this.g,a);this.dispose()};
s7.prototype.disconnect=s7.prototype.A;s7.prototype.X=function(){var a=this.Pa;this.l&&(a=this.Pa.clone(),f7(a,this.l,a.index));return g7(a)};
s7.prototype.getPlayerContextData=s7.prototype.X;
s7.prototype.ka=function(a){var b=new a7(a);b.videoId&&b.videoId!=this.Pa.videoId&&(this.l=b.videoId,g.fq(this.F),this.F=g.dq((0,g.y)(this.qL,this),5E3));var c=[];this.Pa.listId==b.listId&&this.Pa.videoId==b.videoId&&this.Pa.index==b.index||c.push("remoteQueueChange");this.Pa.playerState==b.playerState&&this.Pa.volume==b.volume&&this.Pa.muted==b.muted&&e7(this.Pa)==e7(b)&&g.Wg(this.Pa.g)==g.Wg(b.g)||c.push("remotePlayerChange");this.Pa.reset(a);(0,g.A)(c,function(a){this.M(a)},this)};
s7.prototype.setPlayerContextData=s7.prototype.ka;s7.prototype.V=function(){var a=this.g.A.id,b=g.eb(this.i,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
s7.prototype.getOtherConnectedRemoteId=s7.prototype.V;s7.prototype.D=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.B)():NaN};
s7.prototype.getReconnectTimeout=s7.prototype.D;s7.prototype.aa=function(){return this.o||"UNSUPPORTED"};
s7.prototype.getAutoplayMode=s7.prototype.aa;s7.prototype.Y=function(){return this.B||""};
s7.prototype.getAutoplayVideoId=s7.prototype.Y;s7.prototype.oa=function(){if(!isNaN(this.D())){var a=this.g.i;g.Eo(a.g);a.start()}};
s7.prototype.reconnect=s7.prototype.oa;s7.prototype.fa=function(a,b){y7(this,a,b);z7(this)};
s7.prototype.sendMessage=s7.prototype.fa;g.z(D7,e6);g.h=D7.prototype;g.h.Fd=function(a){return this.Dc.$_gs(a)};
g.h.contains=function(a){return!!this.Dc.$_c(a)};
g.h.get=function(a){return this.Dc.$_g(a)};
g.h.start=function(){this.Dc.$_st()};
g.h.add=function(a,b,c){this.Dc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Dc.$_r(a,b,c)};
g.h.Mn=function(a,b,c,d){this.Dc.$_un(a,b,c,d)};
g.h.R=function(){for(var a=0,b=this.i.length;a<b;++a)this.Dc.$_ubk(this.i[a]);this.i.length=0;this.Dc=null;D7.Ha.R.call(this)};
g.h.kM=function(){this.M("screenChange")};
g.h.dJ=function(){this.M("onlineScreenChange")};
r6.prototype.$_st=r6.prototype.start;r6.prototype.$_gspc=r6.prototype.lM;r6.prototype.$_gsppc=r6.prototype.QA;r6.prototype.$_c=r6.prototype.contains;r6.prototype.$_g=r6.prototype.get;r6.prototype.$_a=r6.prototype.add;r6.prototype.$_un=r6.prototype.Mn;r6.prototype.$_r=r6.prototype.remove;r6.prototype.$_gs=r6.prototype.Fd;r6.prototype.$_gos=r6.prototype.PA;r6.prototype.$_s=r6.prototype.subscribe;r6.prototype.$_ubk=r6.prototype.wf;var E7=null,F7=null,V7=null,J7=[];g.r(Y7,g.E);g.h=Y7.prototype;
g.h.R=function(){g.E.prototype.R.call(this);this.o.stop();this.A.stop();this.I.stop();this.N();this.g.unsubscribe("proxyStateChange",this.Iy,this);this.g.unsubscribe("remotePlayerChange",this.lk,this);this.g.unsubscribe("remoteQueueChange",this.Rm,this);this.g.unsubscribe("autoplayUpNext",this.jy,this);this.g.unsubscribe("previousNextChange",this.Fy,this);this.g.unsubscribe("nowAutoplaying",this.By,this);this.g.unsubscribe("autoplayDismissed",this.iy,this);this.g=this.u=null};
g.h.ix=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(b8(this)){if(!k7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==k7(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.zj(c[0],c[1]);break;case "control_subtitles_set_track":c8(this,c[0]);break;case "control_set_audio_track":c=c[0],b8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();d8(this,0==c?void 0:c);break;case "control_seek":d8(this,c[0]);break;case "control_subtitles_set_track":c8(this,c[0]);break;case "control_set_audio_track":c=c[0],b8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.qH=function(a){this.I.zC(a)};
g.h.UL=function(a){this.ix("control_subtitles_set_track",g.nc(a)?null:a)};
g.h.eA=function(){var a=this.i.getOption("captions","track");g.nc(a)||c8(this,a)};
g.h.wy=function(a){if(b8(this)){this.g.unsubscribe("remotePlayerChange",this.lk,this);var b=Math.round(a.volume);a=!!a.muted;var c=k7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.lk,this)}};
g.h.sI=function(){g.nc(this.B)||e8(this,this.B);this.D=!1};
g.h.Iy=function(a,b){this.A.stop();2==b&&this.dA()};
g.h.lk=function(){if(b8(this)){this.o.stop();var a=k7(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.gm=1;break;case 1082:case 1083:this.u.gm=0;break;default:this.u.gm=-1}switch(a.playerState){case 1081:case 1:$7(this,new g.PC(8));this.cA();break;case 1085:case 3:$7(this,new g.PC(9));break;case 1083:case 0:$7(this,new g.PC(2));this.H.stop();Z7(this,this.i.getVideoData().lengthSeconds);break;case 1084:$7(this,new g.PC(4));break;case 2:$7(this,new g.PC(4));Z7(this,e7(a));
break;case -1:$7(this,new g.PC(64));break;case -1E3:$7(this,new g.PC(128,{errorCode:"mdx.remoteerror",message:"Este video no se encuentra disponible para reproducirse de forma remota."}))}a=k7(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,e8(this,a));a=k7(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.DA()}else a8(this)};
g.h.Fy=function(){this.i.M("mdxpreviousnextchange")};
g.h.Rm=function(){b8(this)||a8(this)};
g.h.PB=function(){this.g.Tu()};
g.h.jy=function(a){a&&(a=g.Sq("/watch_queue_ajax",{method:"GET",Ac:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.FK,this)}))&&(this.N=(0,g.y)(a.abort,a))};
g.h.FK=function(a,b){var c=new g.WA(g.V(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.M("mdxautoplayupnext",c)};
g.h.By=function(a){isNaN(a)||this.i.M("mdxnowautoplaying",a)};
g.h.iy=function(){this.i.M("mdxautoplaycanceled")};
g.h.ZE=function(a,b){-1==k7(this.g).playerState?d8(this,a):b&&this.g.seekTo(a)};
g.h.DA=function(){if(b8(this)){var a=k7(this.g);this.l.Na(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.wy)}};
g.h.cA=function(){this.o.stop();if(!this.g.da()){var a=k7(this.g);1==a.playerState&&$7(this,new g.PC(8));Z7(this,e7(a));this.o.start()}};
g.h.dA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.r(h8,g.S);h8.prototype.u=function(a){g8(this,a.state)};g.r(i8,g.cT);i8.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.D=g.Hb(a,this.A,this),g.dT(this,(0,g.D)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.ke(this.A(a)),this.enable(!0)):this.enable(!1)};
i8.prototype.A=function(a){return a.key};
i8.prototype.je=function(a){return"cast-selector-receiver"==a?"Transmitir\u2026":this.D[a].name};
i8.prototype.Wc=function(a){g.cT.prototype.Wc.call(this,a);this.l.setOption("remote","currentReceiver",this.D[a]);this.o.gb()};g.r(j8,g.fK);g.h=j8.prototype;g.h.create=function(){Ppa(g.Ny(g.V(this.player)));this.u.push(g.kq("yt-remote-before-disconnect",this.nH,this));this.u.push(g.kq("yt-remote-connection-change",this.IJ,this));this.u.push(g.kq("yt-remote-receiver-availability-change",this.Gy,this));this.u.push(g.kq("yt-remote-auto-connect",this.GJ,this));this.u.push(g.kq("yt-remote-receiver-resumed",this.FJ,this));this.Gy()};
g.h.load=function(){this.player.cancelPlayback();g.fK.prototype.load.call(this);this.o=new Y7(this,this.player,this.g);var a=(a=X7())?a.currentTime:0;var b=U7()?new j7(P7(),void 0):null;0==a&&b&&(a=e7(k7(b)));0!=a&&this.nd(a);f8(this,this.Xj,this.Xj);g.fX(this.player.app,6)};
g.h.unload=function(){this.player.M("mdxautoplaycanceled");this.l=this.i;g.Ff(this.o,this.g);this.g=this.o=null;g.fK.prototype.unload.call(this);g.fX(this.player.app,5)};
g.h.R=function(){g.lq(this.u);g.fK.prototype.R.call(this)};
g.h.Pe=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.o.ix.apply(this.o,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.gm};
g.h.vC=function(){return this.loaded?this.o.suggestion:null};
g.h.Ee=function(){return this.g?k7(this.g).Ee:!1};
g.h.hasNext=function(){return this.g?k7(this.g).hasNext:!1};
g.h.nd=function(a,b){this.D=a||0;this.player.M("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.D};
g.h.getProgressState=function(){var a=k7(this.g),b=this.player.getVideoData();return{allowSeeking:g.P(g.V(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Zb():!a.isAdPlaying()&&this.player.Zb(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+c7(a):a.l,isAtLiveHead:1>=(a.u?a.i+c7(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+c7(a):a.i,seekableStart:0<a.o?a.o+
c7(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Zm=function(){this.g&&this.g.Zm()};
g.h.nH=function(a){1==a&&(this.B=this.g?k7(this.g):null)};
g.h.IJ=function(){var a=U7()?new j7(P7(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.B=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.Ef(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.B)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,e7(a)));this.player.M("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Gy=function(){this.A=[this.i].concat(Qpa());var a=Q7()||this.i;k8(this,a);this.player.ma("onMdxReceiversChange")};
g.h.GJ=function(){var a=Q7();k8(this,a)};
g.h.FJ=function(){this.l=Q7()};
g.h.Vb=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?Z6():k8(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&Z6(),!0):!1}};
g.h.Hs=function(){this.g.Hs()};
g.h.Lb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.sU.remote=j8;})(_yt_player);
